### ISSUE TITLE
DateTimeFormat bug

### ISSUE THREAD

**Issue by freddyboucher** [gwtproject/gwt#9427] opened 2016-09-20 01:14 UTC
Primarily discussed here: https://groups.google.com/forum/#!topic/google-web-toolkit/F_DiVaouKzE

The following **DateTimeFormatTest#notWorking()** fails (GWT 2.7.0).

```java
package com.google.gwt.i18n.shared;

import com.google.gwt.i18n.client.TimeZone;
import com.google.gwtmockito.GwtMockitoTestRunner;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.util.Date;

@RunWith(GwtMockitoTestRunner.class)
public class DateTimeFormatTest {
    @Test
    public void working() {
        Date date = new Date(1457395200000l);
        DateTimeFormat format = DateTimeFormat.getFormat(DateTimeFormat.PredefinedFormat.ISO_8601);
        String formattedDate = format.format(date, TimeZone.createTimeZone(0));

        Assert.assertEquals("2016-03-08T00:00:00.000+00:00", formattedDate);
        Assert.assertEquals(date, format.parse(formattedDate));
    }


    @Test
    public void notWorking() {
        Date date = new Date(1459639080000l);
        DateTimeFormat format = DateTimeFormat.getFormat(DateTimeFormat.PredefinedFormat.ISO_8601);
        String formattedDate = format.format(date, TimeZone.createTimeZone(0));

        Assert.assertEquals("2016-04-02T23:18:00.000+00:00", formattedDate);
        Assert.assertEquals(date, format.parse(formattedDate));
    }
}
```

Results:
- **DateTimeTest#working()**: OK
- **DateTimeTest#notWorking()**: The formatted date is wrong (see following logs). There is one day difference between **Actual** and **Expected**. (You can ensure **Expected** is correct by running the following **SimpleDateFormatTest#simpleTest()** (it runs in the JVM))

Logs:
```java
objc[60568]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.

org.junit.ComparisonFailure: 
Expected :2016-04-02T23:18:00.000+00:00
Actual   :2016-04-03T23:18:00.000+00:00
  <Click to see difference>



	at com.google.gwt.i18n.shared.DateTimeFormatTest.notWorking(DateTimeFormatTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.gwtmockito.GwtMockitoTestRunner.run(GwtMockitoTestRunner.java:301)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)


Process finished with exit code 255
```

**SimpleDateFormatTest** runs in JVM for comparison purpose:
```java
package com.google.gwt.i18n.shared;

import org.junit.Assert;
import org.junit.Test;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

public class SimpleDateFormatTest {
    @Test
    public void simpleTest() throws ParseException {
        Date date = new Date(1459639080000l);
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZZZ");
        format.setTimeZone(java.util.TimeZone.getTimeZone("UTC"));
        String formattedDate = format.format(date);

        Assert.assertEquals("2016-04-02T23:18:00.000+0000", formattedDate);
        Assert.assertEquals(date, format.parse(formattedDate));
    }
}
```

I tested the following patch https://gwt-review.googlesource.com/#/c/14430/ and it fixes the problem.

**Comment by tbroyer** [comment] 2016-09-26 13:42
Dupe of #8259

**Closed by tbroyer** 2016-09-26 13:42 UTC
