### ISSUE TITLE
Method reference doesn't work with PRETTY code style

### ISSUE THREAD

**Issue by dmuslymov** [gwtproject/gwt#9664] opened 2019-07-17 14:42 UTC
**GWT version:** 2.8.2
**Browser (with version):** Google Chrome Version 70.0.3538.102 (64-bit)
**Operating System:** Ubuntu 18.04.1 LTS
---

##### Description

I'm getting an error at runtime in browser console when project is compiled with 'PRETY' style flag, when obfuscated everything is alright.

Error in browser console when launching an application: "Uncaught SyntaxError: Unexpected token <"
The place in compiled code where I get an error is function definition:
`function PumpTablePresenter$0methodref$ctor$Type(com_example_face_common_client_tableview2_table_PumpTablePresenter<T>){...}`

Source code line where the problem is located looks like this:
`protected F1<Integer, ApplicationCallback<Batch<T>>> callbackGenerator = PumpTableApplicationCallback::new;`

##### Known workarounds

Changing method reference to lambda helps to get rid of an error

**Comment by niloc132** [comment] 2019-07-17 15:34
We use method references to create generic types in PRETTY without issue - could you share the rest of the source for these types, or at least enough to make a reproducible sample? F1, ApplicationCallback, Batch, PumpTableApplicationCallback at least, with empty method bodies (except to return some appropriate value to make the compiler not rewrite into just `null`s or something)?

**Comment by axeluhl** [comment] 2019-10-12 16:05
We face a similar issue, on gwt-2.8.2. We have two classes, say A and B, each with a public static inner class; both inner classes are called C and have a type parameter T that extends some other class S. Both C classes have a method

  public void m(final T t) {...}

In some other class D we're now using method references to those m methods (A.C::m and B.C::m, respectively) within the same method. In PRETTY mode we're ending up with

Caused by: com.google.gwt.core.client.JavaScriptException: (ReferenceError) : D$2methodref$m$Type_2_g$ is not defined

ReferenceError: D$2methodref$m$Type_2_g$ is not defined

This sounds at least very similar to the original bug report here. It seems to me from the error message that identifiers are being generated (D$2methodref$m$Type_2_g$) that do not uniquely distinguish between the classes defining the method "m", hence leading to some sort of duplication and subsequently the reference / not defined error.

Nota bene: if we fiddle a bit with the ordering of the lines that make use of these method references, the problem goes away and comes back again. On different installations of our development environment there are different outcomes of this, depending on how we change the order of method references. It almost seems as if something was inserted by name into some hashed structure where hash codes are more or less random.

**Comment by axeluhl** [comment] 2019-10-12 16:52
Reproduction code:

D.java:
--------
public class D {
    public void someMethod() {
        reproduceGWTBug();
    }

    private void reproduceGWTBug() {
        final A1.C<String> instance1 = new A1.C<>();
        final Consumer<String> methodReference1 = instance1::m;
        final A2.C<String> instance2 = new A2.C<>();
        final Consumer<String> methodReference2 = instance2::m;
        GWT.log("created method references successfully: "+methodReference1+", "+methodReference2);
    }
}

A1.java:
---------
public class A1 {
    public static class C<T> {
        public void m(final T t) {}
    }
}

A2.java:
public class A2 {
    public static class C<T> {
        public void m(final T t) {}
    }
}

Error: com.google.gwt.user.client.ui.AttachDetachException: Exception caught: (ReferenceError) : D$2methodref$m$Type_4_g$ is not defined

I've tried reproducing without the "T" type parameter and using some regular type for the "t" parameter but was unable to reproduce the problem.

In some cases, the above code didn't cause the error right away. Then, swapping the order of the lines

        final A1.C<String> instance1 = new A1.C<>();
        final Consumer<String> methodReference1 = instance1::m;

and the lines

        final A2.C<String> instance2 = new A2.C<>();
        final Consumer<String> methodReference2 = instance2::m;

caused the error again.

**Comment by rluble** [comment] 2019-10-12 17:40
Is this using superdevmode or a batch compile with `-style PRETTY`? By the look of the identifiers this those "pretty" names are generated by the `JsIncreamentalNamer` (superdevmode) not the `JsPrettyNamer` (`-style PRETTY`). So this is probably a duplicate of #9670 and not related to the namer but to the incremental compilation not realizing that a class has changed.

Could you post a simple standalone repro project where the issue is reproduced in a batch compile?

**Comment by axeluhl** [comment] 2019-10-12 18:41
Yes, it's the incremental compiler and SuperDevMode. I'll see if I can find the time to isolate this into a standalone project. I understand that this helps a lot to reproduce and subsequently fix, but carving this out of a tricky project using GWT in an OSGi/embedded Jetty environment will take some time.

Before I start with this, how do you see chances to get a fix for this underway that would be in a 2.8.x release still?

**Comment by axeluhl** [comment] 2019-10-12 19:17
https://github.com/axeluhl/gwtbug9670

**Comment by rluble** [comment] 2019-10-12 23:16
Since this is only in superdevmode, it is a duplicate of #9670. Closing.

**Closed by rluble** 2019-10-12 23:16 UTC

**Comment by rluble** [comment] 2019-10-12 23:18
Colin was working on fixing that bug; Since there is no fix yet I don't think it will make it to next release. But let's follow the discussion in the other end.
