### ISSUE TITLE
UIObject#getAbsoluteTop / getAbsoluteLeft is broken in Chrome 61+

### ISSUE THREAD

**Issue by Leonya** [gwtproject/gwt#9548] opened 2017-09-18 21:48 UTC
The methods return incorrect results when the page itself is scrolled. More info can be found here:

https://www.reddit.com/r/webdev/comments/6ygn2s/chrome_devs_have_decided_to_break_scrollto_auto/

https://dev.opera.com/articles/fixing-the-scrolltop-bug/

It seems that Firefox 55 rolled out the same behaviour change simultaneously.

**GWT version: 2.8.1** 
**Browser (with version): Chrome 61.0.3163.91** 
**Operating System: Any** 

##### Known workarounds

I've implemented the following methods utilising modern APIs and have replaced my usages of the built-in methods:

```
  public static native int getOffsetTop(Element element) /*-{
    return element.getBoundingClientRect().top + $doc.scrollingElement.scrollTop;
  }-*/;

  public static native int getOffsetLeft(Element element) /*-{
    return element.getBoundingClientRect().left + $doc.scrollingElement.scrollLeft;
  }-*/;
```

**Comment by tbroyer** [comment] 2017-09-19 07:04
Duplicate of #9542

**Closed by tbroyer** 2017-09-19 07:04 UTC
