### ISSUE TITLE
java.util.Collections.copy(List dest, List src) appends dest instead of overwriting.

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#9123] opened 2015-06-10 20:12 UTC
Originally reported on Google Code with ID 9194
```
Found in GWT Release (e.g. 2.4.0, 2.5.1, trunk):

GWT 2.7.0 and below.

Encountered on OS / Browser (e.g. WinXP, IE9, FF10):

n/a

Detailed description (please be as specific as possible):

java.util.Collections.copy(List<? super T> dest, List<? extends T> src) is supposed
to overwrite dest, but the GWT implementation appends it:

public static <T> void copy(List<? super T> dest, List<? extends T> src) {
    // TODO(jat): optimize
    dest.addAll(src);
}

From the Java documentation: "Copies all of the elements from one list into another.
After the operation, the index of each copied element in the destination list will
be identical to its index in the source list. The destination list must be at least
as long as the source list. If it is longer, the remaining elements in the destination
list are unaffected."

Shortest code snippet which demonstrates issue (please indicate where
actual result differs from expected result):

ArrayList<Integer> dst = new ArrayList<>();
ArrayList<Integer> src = new ArrayList<>();
dst.add(1);
src.add(2);
Collections.copy(dst, src);
boolean correct = dst.size() == 1 && dst.get(0).equals(2);

expected: dst == [2]
actual result: dst == [1,2]


```

Reported by `pghjvanblokland` on 2015-04-30 12:13:47

**Comment by nordligulv** [comment] 2015-06-11 12:01
The issue is fixed in commit 450bfa58

**Closed** 2015-12-05 04:54 UTC
Labels: Category-JRE, FixedNotReleased, Milestone-2_8
