### ISSUE TITLE
JVM crash originating from AutoBeanUtils.getAutoBean/ShimHandler.maybeWrap

### ISSUE THREAD

**Issue by rakeshw** [gwtproject/gwt#9529] opened 2017-06-22 17:12 UTC
2.8.0
Browser (with version): Not applicable
Operating System: Red Hat Enterprise Linux
APP server: Jboss EAP 7
JDK: 180_102
Java: 8

---
We are seeing random JVM crashes in our prod environment. CPU is normal, but there is a heap spike just before the crash. Thread dump tells us that the shimhandler mechanism is autobean is failing while parsing the payload. See the exception stac trace attached here. 

---

Steps to reproduce
Unfortunately we don't know. This is happening randomly in production. We were not able to link it to any user action. We have never seen this exception in or dev of test environments. 

---

Known workarounds: 
Would love to know. 

---

Links to further discussions
I have posted discussion thread with similar subject in gwt groups, however the thread has not yet surfaced. 

---

Here's the relevant stack: 

Stack: [0x00007f867d742000,0x00007f867d843000],  sp=0x00007f867d840ab0,  free space=1018k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
J 31252 C2 com.google.web.bindery.autobean.shared.AutoBeanUtils.getAutoBean(Ljava/lang/Object;)Lcom/google/web/bindery/autobean/shared/AutoBean; (21 bytes) @ 0x00007f8b00782b0c [0x00007f8b00782880+0x28c]
J 37685 C2 com.google.web.bindery.autobean.vm.impl.ShimHandler.maybeWrap(Ljava/lang/Class;Ljava/lang/Object;)Ljava/lang/Object; (103 bytes) @ 0x00007f8affd3f9ac [0x00007f8affd3f960+0x4c]
J 35743 C2 com.google.web.bindery.autobean.vm.impl.ShimHandler.invoke(Ljava/lang/Object;Ljava/lang/reflect/Method;[Ljava/lang/Object;)Ljava/lang/Object; (221 bytes) @ 0x00007f8b01706ed8 [0x00007f8b01706940+0x598]
J 37720 C2 com.google.web.bindery.autobean.shared.impl.AutoBeanCodexImpl$MapCoder.encode(Lcom/google/web/bindery/autobean/shared/impl/AutoBeanCodexImpl$EncodeState;Ljava/lang/Object;)V (360 bytes) @ 0x00007f8affd49ee0 [0x00007f8affd49920+0x5c0]
J 37750 C2 com.google.web.bindery.autobean.shared.impl.AutoBeanCodexImpl$PropertyGetter.encodeProperty(Ljava/lang/String;Ljava/lang/Object;Lcom/google/web/bindery/autobean/shared/AutoBeanVisitor$PropertyContext;)V (93 bytes) @ 0x00007f8b01e45b58 [0x00007f8b01e455c0+0x598]
J 39466 C2 com.google.web.bindery.autobean.shared.impl.AutoBeanCodexImpl$PropertyGetter.visitReferenceProperty(Ljava/lang/String;Lcom/google/web/bindery/autobean/shared/AutoBean;Lcom/google/web/bindery/autobean/shared/AutoBeanVisitor$PropertyContext;)Z (18 bytes) @ 0x00007f8affaa6da8 [0x00007f8affaa6d40+0x68]
J 35602 C2 com.google.web.bindery.autobean.vm.impl.ProxyAutoBean.traverseProperties(Lcom/google/web/bindery/autobean/shared/AutoBeanVisitor;Lcom/google/web/bindery/autobean/shared/impl/AbstractAutoBean$OneShotContext;)V (448 bytes) @ 0x00007f8aff2050cc [0x00007f8aff204600+0xacc]
J 42352 C2 com.google.web.bindery.autobean.shared.impl.AutoBeanCodexImpl$CollectionCoder.encode(Lcom/google/web/bindery/autobean/shared/impl/AutoBeanCodexImpl$EncodeState;Ljava/lang/Object;)V (109 bytes) @ 0x00007f8b02af44c0 [0x00007f8b02af4080+0x440]
J 37750 C2 com.google.web.bindery.autobean.shared.impl.AutoBeanCodexImpl$PropertyGetter.encodeProperty(Ljava/lang/String;Ljava/lang/Object;Lcom/google/web/bindery/autobean/shared/AutoBeanVisitor$PropertyContext;)V (93 bytes) @ 0x00007f8b01e45b58 [0x00007f8b01e455c0+0x598]
J 39466 C2 com.google.web.bindery.autobean.shared.impl.AutoBeanCodexImpl$PropertyGetter.visitReferenceProperty(Ljava/lang/String;Lcom/google/web/bindery/autobean/shared/AutoBean;Lcom/google/web/bindery/autobean/shared/AutoBeanVisitor$PropertyContext;)Z (18 bytes) @ 0x00007f8affaa6da8 [0x00007f8affaa6d40+0x68]
J 35602 C2 com.google.web.bindery.autobean.vm.impl.ProxyAutoBean.traverseProperties(Lcom/google/web/bindery/autobean/shared/AutoBeanVisitor;Lcom/google/web/bindery/autobean/shared/impl/AbstractAutoBean$OneShotContext;)V (448 bytes) @ 0x00007f8aff204fb4 [0x00007f8aff204600+0x9b4]
J 39707 C2 com.google.web.bindery.autobean.shared.AutoBeanCodex.encode(Lcom/google/web/bindery/autobean/shared/AutoBean;)Lcom/google/web/bindery/autobean/shared/Splittable; (40 bytes) @ 0x00007f8b021fa89c [0x00007f8b021fa000+0x89c]
J 55999 C2 com.google.web.bindery.requestfactory.server.RequestFactoryServlet.doPost(Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;)V (315 bytes) @ 0x00007f8b03a890c4 [0x00007f8b03a884e0+0xbe4]
J 47925 C2 javax.servlet.http.HttpServlet.service(Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;)V (251 bytes) @ 0x00007f8b01c2a6e0 [0x00007f8b01c2a3e0+0x300]
J 47728 C2 javax.servlet.http.HttpServlet.service(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;)V (125 bytes) @ 0x00007f8affc45e54 [0x00007f8affc45a40+0x414]
J 47946 C2 io.undertow.servlet.handlers.ServletHandler.handleRequest(Lio/undertow/server/HttpServerExchange;)V (334 bytes) @ 0x00007f8b01c41adc [0x00007f8b01c417e0+0x2fc]

**Comment by jnehlmeier** [comment] 2017-06-22 18:09
If the JVM terminates without any OutOfMemoryError, which would indicate a memory leak, then the issue is probably not caused by GWT server code unless there is a bug in the JVM and GWT server code somehow triggers it.

So there is no error message from the JVM and no error message in your OS logs? 

Sometimes OutOfMemoryErrors can not be logged anymore because no memory is available but if you add `-XX:+HeapDumpOnOutOfMemoryError` to your JVM parameters then you should at least see something like:
```
java.lang.OutOfMemoryError: Java heap space
Dumping heap to java_pid4192.hprof ...
Heap dump file created [91901809 bytes in 4.464 secs]
```
on stderr (or stdout) of the JVM process. If that occurs you can actually open the *.hprof file in Eclipse Memory Analyzer to see who is consuming all your heap space.

-- J.

**Comment by rakeshw** [comment] 2017-06-22 18:21
We do have -XX:+HeapDumpOnOutOfMemoryError set in our vmargs. However I do not see an OutOfMemoryError at tie time of crash, either in the heap dump or in jboss server log.

**Comment by rakeshw** [comment] 2017-06-22 20:13
I have attached the thread dump from crash. 

[hs_err_pid149xx.zip](https://github.com/gwtproject/gwt/files/1096047/hs_err_pid149xx.zip)

**Comment by jnehlmeier** [comment] 2017-06-22 20:46
Thanks. The dump shows that the process died because of a segmentation fault
```
siginfo: si_signo: 11 (**SIGSEGV**), si_code: 1 (SEGV_MAPERR), si_addr: 0x000000000170036c
```
which means you either have a hardware memory defect or the JVM tried to access/write to a memory location that:
- was read only
- was assigned to a different process
- was already free'd
- (or the memory pointer was not initialized but I guess that is not the case here because `si_addr` would be 0x0 then)

So it is either a JVM bug or some of your libraries use `com.misc.Unsafe` class (and AFAICT GWT does not use this class) to do low level memory operations. This can corrupt memory and cause a segmentation fault if the library in question has a bug in the code using `Unsafe`.

If you really want to know what is going on you need to reproduce the issue and then debug the JVM itself. I guess I would first install newest Java 8 build (1.8.0_131) to see if it changes anything.

**Comment by rakeshw** [comment] 2017-06-22 21:19
All that makes sense. JDK upgrade is a good idea, but we will have to wait for that. In the meantime let me see if there are any references to Unsafe any where in the application(or 3rd party libs). 

One question still remains though: Why do I see gwt-auto-bea/weak-reference/shim stack? Those exact same references are sighted in all our crashes.

**Comment by jnehlmeier** [comment] 2017-06-22 21:50
It is a bit strange if the stack always shows the same method, could hint at a JIT bug as the code is marked as "compiled Java code". You could try to exclude that method from JIT:

`-XX:CompileCommand=exclude,com/google/web/bindery/autobean/shared/AutoBeanUtils.getAutoBean`

If you are curious, this is taken from:
https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/crashes001.html
https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/crashes002.html#CIHDIBJA
https://docs.oracle.com/javase/8/docs/technotes/tools/unix/java.html#BABDDFII

**Comment by jnehlmeier** [comment] 2017-06-22 21:54
> I just ran a search. There is no use of com.misc.Unsafe in the app and its dependent libraries.

Oh I am sorry, that was a typo. It is `sun.misc.Unsafe`. Updated my previous post.

**Comment by rakeshw** [comment] 2017-06-22 22:03
> It is sun.misc.Unsafe
Didn't find that either.

**Comment by rakeshw** [comment] 2017-06-22 22:05
If I exclude getAutoBean from JIT, I fear that RequestFactory will not work. We use RequestFactory heavily in our app; and we are seeing this issue only in prod (not even in our qa-load env).

**Comment by jnehlmeier** [comment] 2017-06-22 22:30
> If I exclude getAutoBean from JIT, I fear that RequestFactory will not work (will it?)

It should work, but probably a bit slower as JVM can not compile the method to machine code anymore. It has to use its interpreter to run the byte code. JVM usually compiles methods via JIT after some calls to that method and not immediately. So even with JIT that method will probably be executed via interpreter the first few times.

You can always try it locally. If you add `-XX:UnlockDiagnosticVMOptions -XX:+PrintCompilation -XX:+LogCompilation` you see a log entry (in a log file called hotspot.log and on console) every time the JVM compiles a method via JIT. After some requests you should also see that `getAutoBean` has been compiled. If you then add the exclude parameter and restart JVM, you should never see a log saying that `getAutoBean` has been compiled. That way you can verify that the exclude command is active.

**Comment by rakeshw** [comment] 2017-06-22 22:52
Okay, I will try the JIT exclude approach. Though that does not seem to be a permanent solution. To fix the root cause, so far I have only two things: 
1. Upgrade java to 1.8.0_131
2. Analyze the payload  at the time of exception (trap it, and write it to a log file)

What do you think about 2? It looks like the crash is happening when gwt's request factory code is trying to parse the payload. If we get to know what the payload is, we can device ways to either avoid or pre process that payload. It will generate a lot of logs for us thought. Thoughts?

**Comment by tbroyer** [comment] 2017-06-23 05:57
AFAICT, the stack shows RF serializing the response, not parsing the request. FWIW.

**Comment by jnehlmeier** [comment] 2017-06-23 14:17
> 1. Upgrade java to 1.8.0_131
> 2. Analyze the payload at the time of exception (trap it, and write it to a log file)

Well I think your only option is updating Java and cross fingers. Otherwise you have to figure out how to reproduce the issue reliably, which seems pretty tough in your case as it only happens in production. But only then you can open a bug against Java itself so that JVM engineers can analyze it.

I am closing this issue for now, because from a GWT point of view we can not do anything about it.

**Closed by jnehlmeier** 2017-06-23 14:17 UTC
Labels: NeedsInfo

**Comment by rakeshw** [comment] 2017-06-23 23:37
Actually Java was upgraded couple of weeks back, and it is at 1.8.0_131. 

Btw, another crash this morning. Log attached. 
[hs_err_pidxxx1.zip](https://github.com/gwtproject/gwt/files/1099250/hs_err_pidxxx1.zip)

To me the crash looks very similar to the earlier one.

**Comment by rakeshw** [comment] 2017-06-23 23:40
@jnehlmeier  can you reopen the topic, since the proposed solution (JDK upgrade) did not help? Or, is there any other idea/thought?

**Comment by tbroyer** [comment] 2017-06-24 09:33
Try without appdynamics javaagent?

In any case, I don't see a reason to reopen this issue: even if some GWT code was causing a JVM crash, the bug would be in the JVM, there's nothing (until proven otherwise) that could be done from a GWT standpoint (as Jens already said).

**Comment by koka424** [comment] 2019-12-06 18:56
@rakeshw did you ever figure out what was going on? We have an issue almost identical to yours.
