### ISSUE TITLE
Suggestion: How To Support GWT SuperDevMode + SSL

### ISSUE THREAD

**Issue by pezaremba** [gwtproject/gwt#9277] opened 2016-02-07 16:30 UTC
I keep seeing complaints/request for SuperDevMode+SSL support, and it being pushed off for various reasons.  I have a suggestion that should be a reasonable request and satisfy us developers who have already figured out how to use an SSL terminating proxy in front of GWT and our Business Logic back-ends.

The SuperDevMode code generator should have either a Method or a String Constant somewhere that sets up the "scheme://host:port/" for all URLs it generates during compilation.

Please give us the ability to pass a value in for this.  I'm _perfectly happy_ using an SSL terminating proxy on the front-end, because that's how I'm going to run the product in the real world, but with everyone pushing for SSL everywhere, not being able to run SuperDevMode behind SSL without using a third party product to re-write every URL in its output is a very real pain point.

**Comment by tbroyer** [comment] 2017-11-13 09:35
Duplicate of #7535

**Closed by tbroyer** 2017-11-13 09:35 UTC
Labels: Category-SuperDevMode
