### ISSUE TITLE
compiling issue about generated class with super dev mode in gwt 2.8

### ISSUE THREAD

**Issue by wangtao** [gwtproject/gwt#9470] opened 2016-12-06 06:33 UTC
After trying to replace classic mode with super dev mode for some days,  we found some problems for our work.

in our case, we have created some "generator mechanisms" to generate utility class source for simulating some java refection system by using gwt generator. 

for instance :   A class (let's say : Customer.java) with some particular annotation, will be constructed and used in the utility class which created by the generator above.

it means that the class  "Customer" is not referenced in other places directly except the utility class, however, this behavior will cause some problems to us in super dev mode 2.8

if we add a new class(let's say : Production) to our project, then we refresh the web page, the code server will recompile the incremental part and the new class(can be found in DEBUG log), however, the  generator will not be executed in this time and the generated utility class remains unchanged. it means that it has no awareness of new class : Production.

but if we just add some reference point in other places manually, for example, a statement in other class : 

....
Production p;
....

then the generator will be activated and all our mechanisms works fine.

generators will be executed every time in classical dev mode,  however, it seems that they will not be called in super dev mode if we have just add a new class and none use it in project source.

so the question is : 

is there a way or option to let generators always be executed in changed recompiling time in super dev mode. 

Thanks !

**Comment by jonl-percsolutions-com** [comment] 2016-12-06 19:29
If you are not using information from the gwt compile context, one option would be to convert your generator to a java annotation processor, then the processor would be run at java compile time instead.  Then you add the annotation processor to your classpath and depending on IDE set some settings and that is it.

**Comment by wangtao** [comment] 2016-12-07 05:52
Thanks for the reply!

Actually, we are currently needing such information(TypeOracle,  getSubtypes and so on) from generator context. 

some of our generators have been migrated to apt tools,  but some of them remained. so we hope that the generators work correctly in super dev mode,  at least for current version of gwt (2.8) .

for the future version of the GWT(for instance : GWT3 or J2CL), if the generator mechanism will be removed from compiler system, then we hope that there will be some similar features instead of generators for our migration work.

Thanks again !

**Comment by tbroyer** [comment] 2016-12-07 10:52
AFAIK, the GWT-RPC generator works in a similar way and doesn't have issues, so there's probably something you do (or don't do) in your generator that triggers the bug. Have a look at it (mostly in `com.google.gwt.user.rebind.rpc.ProxyCreator` AFAICT) to try to understand what differs from your generator (note that the GWT-RPC generator is an `IncrementalGenerator` to be as fast as possible, which also makes it more complex).
As a workaround, simply "touching" the class that's passed to `GWT.create(…)` should be enough to trigger the generator, without the need to restart SDM or clear its cache or run it in non-incremental mode.

Because the GWT-RPC generator doesn't exhibit any similar issue despite working in a similar way (classes aren't necessarily referenced explicitly anywhere else in the client code), this is likely not a bug in GWT though.

**Comment by wangtao** [comment] 2016-12-08 03:34
Hey tbroyer, thanks for your hint and I have cloned a copy of source code of gwt 2.8 and now I am working on finding out what the reasons of the problem are.

as you mentioned, if there is a place that "touching" the new class, then the generator will be triggered correctly.

in our case, we created some mechanisms to emulate java reflect system and class loader system, and uses it in some loose coupling cases. (well... a similar scene :  start a Activity by using an action(a string name) intent in Android) 

1, define a interface and annotation,  let's say :  **ClassType**

2, define a utility class as the gwt world tree.  let's say : **WorldTreeClassLoader** and its abstract method
"<T> T newInstance(String className)"

3, define a generator,  to match the class **WorldTreeClassLoader**,  in generator, acquire all the sub types(A, B, C and so on) of class "**ClassType**" and then create a sub class(**ClassLoaderDelegator**) of the **WorldTreeClassLoader** and  complete "newInstance" method body, for instance : 

using a switch case

 switch <hashcode of className>
     case hashcode of A : { return new A(); } 
     case hashcode of B : { return new B(); } 

.........

-----------------------------------
so that is the question, there is no place touching the A, B, C directly except generated delegator class, if I somehow triggered generator in other ways so that the ClassLoaderDelegator can put the A, B, C in its source, then the later changes that will affect the content of ClassLoaderDelegator (for instance : modify, delete A, B, C....) will trigger the generator correctly. 

but for the first time that I create a new class ( of the sub type of ClassType ) will not trigger the generator.


I also noticed the log for such problem is different ：

add a new class( N.java,  **not yet in ClassLoaderDelegator**) 
-------------------------------------------------
known modified types = [ N ]             //   **found N**
known modified resources = []
clearing cached output for resulting stale types = []
.....
Compiling 1 permutation                    //   **begin compiling...**



modify or delete a class( A.java, **already in ClassLoaderDelegator**)
-------------------------------------------------------
known modified types = [A]                        //   **found N**
known modified resources = []
clearing cached output for resulting stale types = [  <the classes that touching the delegator by using GWT.create....>,   A   ]
Computing all possible rebind results for             // **because the stale types have been cleared, so the generators triggered...**
......
known modified types = [A,  ClassLoaderDelegator.... ]      // **ClassLoaderDelegator changed correctly.**
......
Compiling 1 permutation                    //   **begin compiling...**
 

--------------------------------------------------------------------------

it seems that the first case didn't clear stale types correctly in spite of class N will affect the resulting.  so generator will not be triggered.


Now I am working on investigating why this difference exists in the log.  if I have some progress I will reply here.

thanks again !

**Comment by wangtao** [comment] 2016-12-08 09:16
I made some investigation in gwt sdk 2.8.0 according to the log output and found these codes in MinimalRebuildCache.java

--------------------------------------------------------------------------------------------------------

    staleTypeNames.clear();

    Set<String> modifiedTypeNames = computeModifiedTypeNames();

    // Accumulate the names of stale types resulting from some known type or resource modifications,
    // using various patterns (sub types, referencing types, etc).
    {
      staleTypeNames.addAll(modifiedTypeNames);
      appendSubTypes(staleTypeNames, modifiedTypeNames, typeOracle);
      // Marks stale any type that references either a modified type or any subtype of a modified
      // type. The references of subtypes can be done away with once we revamp Array castmap
      // generation.
      ImmutableList<String> modifiedTypeAndSubTypeNames = ImmutableList.copyOf(staleTypeNames);
      appendReferencingTypes(staleTypeNames, modifiedTypeAndSubTypeNames);
      appendReferencingTypes(staleTypeNames, jsoStatusChangedTypeNames);
      staleTypeNames.addAll(
          computeTypesThatRebindTypes(computeReboundTypesAffectedByModifiedResources()));
      appendTypesToRegenerateStaleGeneratedTypes(staleTypeNames);

      // Generator output is affected by types queried from the TypeOracle but changes in these
      // types are not being directly supported at this time since some of them are already handled
      // because they are referenced by the Generator output and since changes in subtype queries
      // probably make GWTRPC output incompatible with a server anyway (and thus already forces a
      // restart).

      staleTypeNames.removeAll(JProgram.SYNTHETIC_TYPE_NAMES);
    }

    /*
     * Filter for just those stale types that are actually reachable. Since if they're not reachable
     * we don't want to artificially traverse them and unnecessarily reveal dependency problems. And
     * if they have become reachable, since they're missing JS, they will already be fully traversed
     * when seen in Unify.
     */
    copyCollection(filterUnreachableTypeNames(staleTypeNames), staleTypeNames);    // line 333

-------------------------------------------------------------------------------------------------------

Here, I made the generator works fine by just commenting line 333,  it is logical solution to avoid unnecessary compiling cost, however in our case, any changes including the new class(even if none of classes refer it) should be always considered as a trigger since they may affect the generator output. 

we hope that there are some strategies or options can take our case into account in the future.

for now, I patched this class for our case, for super dev mode.

Thanks for everyone's help!

**Comment by tbroyer** [comment] 2016-12-08 12:55
Note that when I said "touching" I meant it in the sense of the Unix `touch` command: touching the `WorldTreeClassLoader` would re-trigger the generator.

Some more notes:
 * have you checked if this is a problem with GWT-RPC? (make a simple RPC that transports some class A, then add B as a new subclass of A: does it retriggers the GWT-RPC generator?)
 * have you checked if running SDM with `-noincremental` would workaround the issue?
 * if it is also a problem with GWT-RPC, then it is a limitation of the incremental compiler. Given the specific work done by those generators basically traversing the whole source path, I'm not keen on calling it a bug, but rather a limitation. Also note that it's quite unlikely that this would be changed/fixed unless someone contributes the patch: we've been saying for more than a year now that it was seen as a design-flaw of GWT-RPC that wouldn't be carried along in the long term.
 * regarding J2Cl and the future of GWT (still unsettled, though likely based on J2Cl), as I just said, it's unlikely that any similar mechanism will ever exist (well, it's known for sure that it won't be in J2Cl proper at least), you'll have to move to a different way of doing things. It might be possible to do it with an annotation processor set to trigger on `"*"`, passing as an option (or in a file that you'd generate first, out-of-band, before calling JavaC) the full list of packages to inspect (annotation processors cannot traverse the package hierarchy, they don't see subpackages of a package, only classes); or as a tool you'd run after JavaC and that'd scan the classpath (it could then even call JavaC through `javax.tools.JavaCompiler` to generate a compiled version of the class).

**Comment by wangtao** [comment] 2016-12-09 05:03
Hey Tbroyer, thanks for your patient reply!

I have checked the GWT-RPC generator, and I am afraid that it may face the same problem, 

first of all, we are currently using rest api as our server side instead of gwt-rpc, so I just made some tests

I created following classes : 

- public interface DataService extends RemoteService  {   BeanA get(); }

- public interface DataServiceAsync  { void get(AsyncCallback<BeanA> callback); }

- public class BeanA

- public class BeanB extends BeanA                                 

-----------------------------------------------
BeanB class was added after first compiling, however, none(including  ServiceInterfaceProxyGenerator...)  triggered for this event.

the logs just as I mentioned before

-----------------------------------------------

known modified types = [ BeanB ]
known modified resources = []
clearing cached output for resulting stale types = []
......
Compiling 1 permutation


Further, no generator triggered even I modified these classes : DataService,  DataServiceAsync , BeanA because none of others refer them for now.

then, I create a class Test, and add a statement to refer DataService : 

public class Test {   DataService ds ;  }

the generator triggered.

after that, I modified BeanA(yes, BeanA) and BeanB, none triggered

if I modified DataService or Test,  generator triggered

since BeanA will NOT trigger the generator too, I guess that the compiler may just check the reference directly, for instance : DataService will trigger the generator.



the good news is running SDM with -noincremental will work around this issue.


about J2Cl and the future of GWT, actually we have already made some work on it, including some annotation processor,  maven plugin and IDE plugin(for instance : generating our rest api client stub by eclipse builders plugin), however, our projects are more complex than a single module, it includes many individual deps or libs(our or others') with or without source ( for these gwt modules),  when working on a particular module, for these IDE plugins(Builders) or annotation processors work in source level , they may know(or concern) nothing about class source in other modules, especially some of them are not used directly but affect the last result. these source codes are only necessary for gwt compiler.

however If compiler is sure to translate the java source to java script no matter what the way is, we believe that there must be some cut-in point ( like AOP or compiler interceptor) before the translating process, and these mechanisms can be used to acquire the necessary meta data(type, annotation, hierarchy...) for us to construct the gwt vm world.

well... It's too early for these topics,  after all they are still unsettled. we will keep a close eye on new version in the future.

Thanks!

**Comment by dankurka** [comment] 2016-12-09 10:03
I think I would ditch GWT generators for what you are doing here entirely.

I would simply go with a Java annotation processor and put an annotation on classes that need reflective capabilities.

**Comment by wangtao** [comment] 2016-12-12 04:35
Hi Dankurka, Thanks for your reply.

we are now working on it.

**Comment by aepshteyn** [comment] 2021-10-30 23:07
@niloc132 Thanks for your suggestions!

It turned out simply that my template loader was caching the template files in memory, which explains why I was having to restart the SDM process in order to pick up the changes.

I can confirm that SDM is correctly re-running my generator when I refresh the browser.

In other words, it was my own fault; nothing wrong with GWT or SDM!

**Comment by niloc132** [comment] 2021-10-31 01:43
Great to hear.

As this is the only traffic on this issue in years, I'm going to go ahead and close this, for other specific issues a new ticket can be filed.

**Closed by niloc132** 2021-10-31 01:43 UTC
Labels: Category-Compiler
