### ISSUE TITLE
Extending native JsTypes from Java with GWT 2.8.0-rc2 results in erroneous js code

### ISSUE THREAD

**Issue by nfekete** [gwtproject/gwt#9430] opened 2016-09-21 13:50 UTC
Having the following declaration (from Elemental2):

```
@JsType(isNative = true, namespace = JsPackage.GLOBAL)
public class HTMLDivElement extends HTMLElement {...}
```
and the extending type

```
public class DummyElement extends HTMLDivElement {...}
```

results in _TypeError: Illegal invocation_ from the compiled js code when it tries to define the class (`com.google.gwt.lang.Runtime.copyObjectProperties (Runtime.java:104)`), while copying native properties from the extended js type's prototype. The property in this case is 'align' but it happens on other browser native properties too.

I created a minimal maven project to reproduce the issue, you can find it at https://github.com/nfekete/gwt-jsinterop-test-01

**Comment by dankurka** [comment] 2016-09-21 13:54
Your example should have 

@JsType(isNative = true, name= "HTMLDivElement" namespace = JsPackage.GLOBAL)
public class HTMLDivElement {...}

Since it is an inner class name would be Outter.HtmlDivElement and there is no native class by that name in the browser.

**Comment by nfekete** [comment] 2016-09-21 14:00
You're right. I added the missing attribute. The error is independent from the missing attribute though, and it's still present after adding the attribute.

**Comment by tbroyer** [comment] 2016-09-21 16:58
Just to say that I reproduce the issue, including with the latest snapshot.

**Comment by gkdn** [comment] 2016-09-21 17:18
We are not suppose to copy the properties from super JsType. The compiler tries to copy the properties from java.lang.Object. This might be suggesting that getPrototypeQualifierViaLookup 
returns incorrect ref which is very surprising.  @rluble?

**Comment by rluble** [comment] 2016-09-21 19:12
The code is generated correctly 

```javascript
defineClass(
  236 /* id of the subclass */, 
  $wnd.HTMLDivElement /* superclass constructor */, {1:1} /* cast map*/,
  cggci.NativeJsTypeTest$ExtendedElement /* subclass constructor */);

/* add java.lang.Object methods to subclass prototype */
copyObjectProperties(
  _ /* subclass prototype set by defineClass */, 
  getClassPrototype(1) /* java.lang.Object prototype */);
```
for some reason "_" does not point to the prototype created by portableObjCreate (called transitively from defineClass) but to HTMLDivElement.

Either this is some kind of JS quirk or there is something I am missing.

**Comment by rluble** [comment] 2016-09-21 19:23
Are native browser types supposed to be subclassed this way? Doesn't this need to be done in the "webcomponents"  style?

**Comment by nfekete** [comment] 2016-09-21 19:56
That was precisely my intent, to register a web component from GWT. I saw a nice presentation from Goktug based on some earlier version of JsInterop/GWT (with the `class CustomElement extends Element.prototype` pattern).

As for the invocation of `Runtime.copyObjectProperties()`, I can tell from running it through the debugger, that it's trying to copy properties from the superclass' prototype, in my case, `HTMLDivElement.prototype`. For me it seemed like when the property copying was happening, the `to[property] = from[property];` line triggered the browser provided native property accessor `get()` function with a `this` pointer assigned to `window`, triggering the exception, window not having the prototype of `HTMLDivElement`, the `get()` function belonging to.  I'm not sure while the act of copying the property triggers the property accessor `get()` method. Maybe there's a work around copying the property without triggering the accessor method?

**Comment by rluble** [comment] 2016-09-21 22:12
You are right in the sense that the copyObjectProperties() is invoked with the parameters in the wrong order.  I just uploaded a patch for review to fix that issue (https://gwt-review.googlesource.com/17020)

IIUC, this scheme works for subclassing regular JS object (such as Error, Object, some other library provided JS classes) but not for subclassing DOM elements. DOM elements are not regular JavaScript classes and subclassing them requires going through the webcomponents API (Element.createElement). GWT does not support this use case directly with JSInterop yet.

That said, I do not know much about webcomponents and defer to @gkdn fill in the details.

**Comment by nfekete** [comment] 2016-09-22 15:08
After minimal testing, it seems that the patch works. I was able to use this for registering custom elements through elemental2's `document.registerElement()`.

**Comment by gkdn** [comment] 2016-09-22 16:57
DOM elements will need to be subclasses for webcomponents.

**Comment by rluble** [comment] 2016-09-23 21:13
Patch merged.

**Closed by rluble** 2016-09-23 21:13 UTC
Labels: Category-JsInterop
