### ISSUE TITLE
GWT 2.7.0 Jetty upgrade to 9.x

### ISSUE THREAD

**Issue by jimmyfm** [gwtproject/gwt#9298] opened 2016-03-15 03:03 UTC
GWT 2.7.0 embedded jetty and outdated dependencies create problems in production environments.

I am working with websockets, and the `@ServerEndpoint` annotation works on my production server but not in the GWT embedded server.

I solved this problem with the `-noserver` parameter but this approach is significantly slower and has a more complicated setup than using the embedded jetty. 
In my case the most time-consuming operation that would be avoided with a new jetty is the server restart which occur quite often in the development process.

**Comment by tbroyer** [comment] 2016-03-15 06:56
Dupe of #8712

**Closed by tbroyer** 2016-03-15 06:56 UTC

**Comment by jimmyfm** [comment] 2016-03-15 14:55
@tbroyer Thank you for the quick response.

The issue #8712 refer to the 2.8 version, while my request is for the current release.

What I am asking for is an hypothetical 2.7.1 release with updated (and maybe maven-ized) dependencies.

**Comment by tbroyer** [comment] 2016-03-15 15:17
That won't happen. The next version will be 2.8.0, there won't be a 2.7.1 (we're close to 2.8 RC1 btw).

Note that instead of `-server` with DevMode, you can also use a separate server and use DevMode with `-noserver` (or use the CodeServer directly, with `-launcherDir`).

**Comment by jimmyfm** [comment] 2016-03-15 15:32
I figured, but it was worth a shot.

We have a very fat Weblogic thus working with `-noserver` is significantly slower.
