### ISSUE TITLE
Different CodeServer host and execution on network system had problem

### ISSUE THREAD

**Issue by thangaraju** [gwtproject/gwt#9527] opened 2017-06-08 21:34 UTC
**GWT version:**  2.8.0
**Browser (with version):**  Chrome
**Operating System:** Windows

---

##### Steps to reproduce

IT has installed MyApp in "hostedsystem" on network.

My codebase is in my local system with host name as "codeserver".

I set "-bindAddress" to "hostedsystem" and "-port" to"9876" Path provided as "\\hostedsystem\MyApp".

It correctly deploys. But, "MyApp.nocache.js" file has entry that codeserver URL as the 'http://' + window.location.host + ':__SUPERDEV_PORT__', which leads to wrong URL generation and ends up "Unable to load code server error".

the fix should in 2 differnet files:
1. stub.nocache.js to change host variable to replace with  'http://' + '__SUPERDEV_BIND_ADDRESS__' + ':__SUPERDEV_PORT__',
2. We need to pass the value for __SUPERDEV_BIND_ADDRESS__ from LauncherDir.java

Can we fix this?

Thanks
Thangaraju

**Comment by tbroyer** [comment] 2017-10-03 16:02
Duplicate of #9446

**Closed by tbroyer** 2017-10-03 16:02 UTC
