### ISSUE TITLE
Unit tests must use different -war directories depending on whether running in -prod mode or in dev mode

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#9102] opened 2015-06-10 20:12 UTC
Originally reported on Google Code with ID 9168
```
Overview:
---------

There is a race condition that arises when running GWT unit tests in -prod (or -web)
mode at the same time as running
them in dev (or hosted) mode with the same "-war" setting (which is the directory where
the linker output will be written)

Example:
--------

When running tests in prod mode (aka "web" mode), com.google.gwt.junit.JUnitShell might
decide that it only needs to compile the
user.agent=gecko1_8 permutation (because the HtmlUnit instance being used as the substitute
for a web browser
is configured to run in its Firefox mode).  This decision speeds up prod mode tests
because it doesn't need to compile
the module permutations for any other browser.  However, the generated `module`.nocache.js
file emitted by the linker
in this case will not include a property getter function for the "user.agent" property
(because its value is fixed to "gecko1_8).

The problem arises next time a unit test in this module is run in dev/hosted mode (without
a -web or -prod flag), because
you will get the following error:

com.google.gwt.core.ext.BadPropertyValueException: Property 'user.agent' cannot be
set to unexpected value '<failed to compute>'

This happens because JUnitShell will be using the old `module`.nocache.js file, that
was emitted when the prod mode tests were compiled.

Detailed investigation:
-----------------------

In GWT 2.5.0, dev mode never clobbers the artifacts emitted by a prod mode compile
due to the following code block
in SelectionScriptLinker.emitSelectionScript:
    /*
     * Last modified is important to keep Development Mode refreses from
     * clobbering Production Mode compiles. We set the timestamp on the
     * Development Mode selection script to the same mod time as the module (to
     * allow updates). For Production Mode, we just set it to now.
     */
    long lastModified;
    if (permutationsUtil.getPermutationsMap().isEmpty()) {
      lastModified = context.getModuleLastModified();
    } else {
      lastModified = System.currentTimeMillis();
    }

In GWT2.7.0, this code was changed to simply:

  long lastModified = context.getModuleLastModified();

(reasons for this change are discussed in https://gwt-review.googlesource.com/#/c/10360/1
)

So in GWT 2.5, the dev mode artifact was only regenerated if any of the module XML
files were modified since last time
whereas the prod mode artifact is always regenerated.
In GWT 2.7, the above change makes the linker always keep the original artifact if
the module XML files haven't been modified.

However, this change doesn't solve the race condition that results from running dev
mode tests after a prod mode test that emitted,
because the JUnitShell in prod mode still only generates the permutation it needs.

A better solution might be to always regenerate the artifact (i.e. set lastModified
= System.currentTimeMillis();),
but it still doesn't solve the race condition.  The only proper solution is to clearly
document and enforce the fact that
dev mode and prod mode unit tests should be run with different -war directories.

Workaround:
-----------
Use different -war directory arguments depending on whether the unit test is being
run in prod or dev mode.






```

Reported by `alexander.epshteyn` on 2015-03-31 22:03:49

**Comment by tbroyer** [comment] 2015-11-09 17:27
Dupe of https://github.com/gwtproject/gwt/issues/9108

**Closed by tbroyer** 2015-11-09 17:27 UTC
Labels: duplicate
