### ISSUE TITLE
Exported Classes implementing JsType interfaces should inherit method annotations

### ISSUE THREAD

**Issue by manolo** [gwtproject/gwt#9313] opened 2016-04-04 19:58 UTC
Given:
```
@JsType interface Int {
  @JsProperty String getA();
}
```

This fails, but as I understand, based on the specification it should work : `the API contract defined by a JsType is still preserved through type hierarchy.`
```
@JsType class Clz implements Int {
   String getA();
}
```

These cases work:
```
class Clz implements Int {
   String getA();
}
@JsType class Clz implements Int {
   @JsProperty String getA();
}
```

IMO, adding the @JsProperty to fix the compiler error looks redundant.

**Comment by manolo** [comment] 2016-04-04 21:38
Same treatment should have other annotations such as `@JsIgnore`

**Comment by rluble** [comment] 2016-06-15 14:51
This should be working. Could you give it a try with the current snapshot? If the JsType is not native you need -generateJsInteropExports otherwise the compiler is allowed prune the super method if there are no callers.

Should also work for JsMethod but not for JsIgnore. JsIgnore is local by design.

**Comment by rluble** [comment] 2016-06-15 17:28
Should be fixed by the patch at https://gwt-review.googlesource.com/#/c/15093

**Closed** 2016-06-18 15:52 UTC
