### ISSUE TITLE
GWT 2.11 and Jetty 9.4.54.v20240208 error running in IntelliJ 2024.1 Ultimate

### ISSUE THREAD

**Issue by dgeiselmanMOO** [gwtproject/gwt#9948] opened 2024-04-10 16:03 UTC
**GWT version:** 2.11
**Browser (with version):** Chrome
**Operating System:** Windows 10

---

##### Description

Build runs fine, but when trying to run the GWT Configuration for my project I am getting an error related to Jetty.

Jetty 9.4.54.v20240208 is giving me
```
Object of class 'com.google.gwt.dev.shell.jetty.JettyLauncher.WebAppContextWithReload' is not of type 'org.eclipse.jetty.webapp.WebAppContext'. Object Class and type Class are from different loaders
```
jetty-web.xml is
```xml
<Configure class="org.eclipse.jetty.webapp.WebAppContext">
 <Set name="maxFormContentSize" type="int">99999999</Set>
 <Get name="securityHandler">
   <Set name="loginService">
     <New class="org.eclipse.jetty.security.HashLoginService">
     	   <Set name="name">mutualofomaha.com</Set>
           <Set name="config"><SystemProperty name="jetty.home" default="."/>/etc/realm.properties</Set>
     </New>
   </Set>
 </Get>
</Configure>
```
WebAppContextWithReload is not mentioned anywhere in my project

Jetty 9.3.30.v20211001 is giving me that it requires ASM 7, and I saw in my dependencies I'm running 9+.

##### Steps to reproduce

Running a GWT application with Jetty and GWT 11 in IntelliJ 2024.1

VM options -Xmx2048m -Xms512m

**Comment by niloc132** [comment] 2024-04-11 00:54
I believe this is a duplicate of https://github.com/gwtproject/gwt/issues/9809, based on the abbreviated stack trace - can you confirm?

**Comment by jnehlmeier** [comment] 2024-04-11 09:33
GWT 2.11 ships with Jetty 9.4.44. 

The error says we have an instance of `WebAppContextWithReload`, provided by GWT SDK, loaded by classloader A but its superclass `WebAppContext`, provided by GWT SDK AND your jetty dependency, is loaded by classloader B.

Why do you have Jetty in your dependencies with scope runtime?

If you customize jetty then you likely cannot use the embedded Jetty provided by GWT SDK. Using the embedded Jetty as a full fledged application server that you can customize has been deprecated for exactly that reason. You should launch your own Jetty, deploy your server application to it and use GWT SDK to only launch SuperDevMode to compile the app to JS.

**Comment by niloc132** [comment] 2024-07-17 15:09
No more details, closing as duplicate.

**Closed by niloc132** 2024-07-17 15:09 UTC
