### ISSUE TITLE
PopupPanel centre() not working on Chrome Ver. 61 on Windows and Linux

### ISSUE THREAD

**Issue by fahad-syed** [gwtproject/gwt#9551] opened 2017-10-02 12:45 UTC
Hi,

The popup panel centre() method is not working on Chrome Ver. 61 on both Windows and Linux. Its aligning the dialogbox to the top.

**GWT version:** 2.6.1
**Browser (with version):** Chrome 6.1
**Operating System:** Windows 10, Linux (Ubuntu 14)

---

**Comment by tbroyer** [comment] 2017-10-02 13:11
This is actually a duplicate of #9542 

Please note that version 2.6.1 is more than 3 years old already, and we only support the latest version (currently 2.8.1); so you'll have to upgrade to 2.8.2 (when released) to get the fix (or fork GWT to cherrypick the commit –bug is already fixed in `master`– and make a custom/patched 2.6 version)

**Closed by tbroyer** 2017-10-02 13:11 UTC
