### ISSUE TITLE
GWT Development Mode Launcher and GWT-DEV external code Issues

### ISSUE THREAD

**Issue by dfht** [gwtproject/gwt#9451] opened 2016-11-05 13:07 UTC
Because the GWT Development Mode Launcher (in GWT Plugins rather than GPE but same applies to both) also runs the code server for superdev mode, it seems that it also puts gwt-dev on the runtime class-path of the server. This causes lots of problems due to GWT-DEV having duplicated code from many other third party jars. In our application, there have been a number of clashes over the last few years. The latest was in the version of Xerces bundled in GWT-DEV, but there have been many more. 
This has led to me eventually using a separate WTP Tomcat server set-up and separate code server that specifies a launcherDir, which of course means the server no longer has this issue and GWT dev is only used by the process that actually needs it - the code server. 
However, this involves more configuration for our users in setting up Tomcat etc. (domain expert developers etc.), and is not ideal. 
Is there a way of using the embedded Jetty on its own without the same launcher/process also running the code server so that I can at least avoid users having to download and set up Tomcat etc.?
Alternatively can the launcher be changed so as to run the code server and embedded Jetty as separate processes under the covers (If it doesn't already !) and hence provide them with different run-time class-paths so the server doesn't have gwt-dev and the code server does (so it would to the user only be starting and stopping a single thing but under the covers there'd actually be two processes)?

**Comment by jnehlmeier** [comment] 2016-11-05 15:34
No you can not launch embedded jetty on its own using DevMode. You would need to write your own main method to start Jetty programmatically.

The usage of the embedded server in GWT is kind of discouraged nowadays because of the issues you encountered. It is generally preferred to create a frontend project that uses GWT (CodeServer or DevMode -noserver) and a dedicated backend project that requires you to provide the server. That way you automatically have two separated class paths and the server you provide can be pretty close to production environment which is always a good thing during development.

If you don't want developers to install a local servlet container then you should use Maven or Gradle for your backend project to launch a servlet container and deploy the project. Another alternative might be a preconfigured Docker container that can deploy a local directory.

**Comment by dfht** [comment] 2016-11-05 15:45
Yes, I know about how to set things up so they do work and with separate server etc. and I think that was clear from what I said: 

'This has led to me eventually using a separate WTP Tomcat server set-up and separate code server that specifies a launcherDir, which of course means the server no longer has this issue and GWT dev is only used by the process that actually needs it - the code server.'

My question is about how to provide a single click out of the box solution for starting without having to set up a separate server - if the embedded Jetty is already there it seems odd that you can just use it as is. I know about running stuff from maven - we use it extensively, but during development it is preferable for us to use Eclipse launchers, and with less technical 'domain expert' developers (we have built a platform that takes most of the drudgery away from such developers) it's nice to give them something out of the box that they can use right away.

I have written a great many Eclipse plug-ins over the years (including many custom launcher types) and I'm sure I can write my own to satisfy the problem - it just surprises me there isn't something there already!

**Comment by dfht** [comment] 2016-11-05 15:59
Anyway, thanks for the pointers. I guess it's not an issue so much, but rather a feature request, but it sounds like I'll have to work something out myself in this case.............

**Comment by branflake2267** [comment] 2016-11-05 16:20
I like one click debugging so I added it to the GWT Eclipse Plugin which fires up gwt development mode when the server WTP runtime starts. Couldn't be easier.  

**Example of click debugging with GWT & Tomcat.** 
https://www.youtube.com/watch?v=LtH4KzmguL0&ab_channel=BrandonDonnelson

**Docs:**
http://gwt-plugins.github.io/documentation/gwt-eclipse-plugin/debugging/GWTDevModeAndTomcatWebServer.html

**Comment by tbroyer** [comment] 2016-11-05 19:26
One of the problems with relying on Maven for the dependencies, is that Maven is designed in such a way that it's impossible to describe 2 distinct dependency trees (for the client-side and server-side parts of your app) in one module; and that means it's quite hard for IDEs to infer the proper classpath and build actions.

What you need is to copy server-side dependencies inside the `WEB-INF/lib` of your "war" lib, and launch DevMode with only the client-side dependencies in the classpath.

Except that DevMode has had that feature from the very beginning that it would use the DevMode classpath as a fallback to the `WEB-INF/lib` when the needed class is not used there (and more accurately, bringing the JAR where the class was found to the webapp classloader just as if it had been in the `WEB-INF/lib`). That was done partly to ease migrations from HostedMode, partly to make it easier to run DevMode as you wouldn't have to first copy your server-side dependencies to the `WEB-INF/lib`. The problem is that this cannot work when the webapp wants to somehow "scan" the classpath, using `ClassLoader#getResources()`: if only the `WEB-INF/lib` JARs (and `WEB-INF/classes`) were included, that'd break the "promise" that you don't have to fist copy your JARs there; and if it "merges" the classpath and the `WEB-INF/lib`, it can break in many other ways (like duplicate resources).

What you can do is provide your own `ServletContainerLauncher` to run Jetty in the same way as the default launcher *except* without the classloader broken tricks. But honestly, just stop using DevMode and move to CodeServer… and if/when using Eclipse, use Brandon's GWT Eclipse Plugin new features.

Maybe we could add a system property or other switch to turn off the special classloader in the embedded Jetty (patches welcome!), but nothing else will happen in GWT proper I'm afraid.

**Comment by dfht** [comment] 2016-11-08 11:20
First I just want to say thanks and to say that I basically agree with all that you've all said about the problems with DevMode and the relative merits of the separate code server approach and I use that a lot already, so it's not a case of moving to the new way (at least for me - my users are a different matter :)). I have now written code in my plug-ins (against WST server core and server core UI code) to set up a Tomcat server and code server launcher with the required set-up I need, so much of the 'drudgery' I referred to earlier (which was just the downloading of e.g. Tomcat , the manual creation of the WTP Tomcat server, the setting of the code server class-path, the insertion of system properties and vm arguments I need into the two kinds of launcher etc.) are all accomplished by a single click now in my set-up. That's all fine and I'll tell my users to follow this approach. It was necessary to avoid these steps for my users. Previously, a single persisted 'dev mode' launcher in one of the projects has accomplished the goal of having a 'ready to use' set-up, which was definitely more simple and elegant.  However, the class-path issues caused by duplication in the GWT-Dev jar have been a constant headache (especially considering Maven's necessary but often troublesome tendency to drag in the whole world via transitive dependencies), and the latest duplication of jars ruining resource look-ups has been the final straw for our use of 'dev mode' launchers I think :).

On a more positive note, the state of GWT and the ease (and speed) of developing with it is (in my opinion) excellent now compared to when we started development on our current platform 3 1/2 years ago. Indeed I have worked with it over many years before that (more or less since it first came out), and compared to back then, well, let's just say that it has come a long long way....
In the last few years we've seen Super Dev mode come along, incremental compilation (now of course even between server restarts even), source maps debugging, JSInterop etc., and what I think have been great strides also in Eclipse and related plug-ins. I'm very very happy with it in general now, although slightly concerned (and puzzled!) about its future direction (GWT 3), especially as it seems to me that it has finally matured into something great....

Whilst I have your attention, let me explain a bit more about my set-up and ask a few more questions.....
My set-up is based on all projects using Maven. I use Eclipse Neon, and I use m2e to entirely manage the class-paths etc. in Eclipse. I have a single lowest level war project  that brings in all of the other projects (there are many of our own GWT modules and of course back-end server projects), so everything is nice and simple for class-paths - this lowest project is enough to specify all dependencies for most purposes (launchers etc.). 

Another ingredient in this soup is the mojo GWT Maven plugin (I'm aware of Thomas's alternative plug-in and I will likely switch to it eventually - for now this works just fine for me).
There are many other ingredients like Spring, WTP natures and above all the fact that most structures are in fact generated from models, but I'll try and stick to what's relevant...

The lowest level war project is a dynamic web module. 

Now to the questions. In my set-up, when (and only when) I run the dev-mode launcher,'something' put's all of the jars (including third party Maven jars and transitive dependencies) into the target/XXX-0.0.1-SNAPSHOT/WEB-INF/lib of the lowest level web project. This only happens when I start the dev mode launcher. It doesn't happen when I build the project in Eclipse (e.g. Project/clean...) or run the M2E 'Maven/Update Project...' action, or even when I start up a standalone Tomcat server on the project (which publishes instead to a folder in the workspace metadata). It ONLY happens when I start the server as a DevMode launcher. It's like the embedded Jetty is using this folder (XXX/target/XXX-0.0.1-SNAPSHOT) as its equivalent to the wtp.deploy folder to 'publish' all of the jars into a war structure... If that is so (and it certainly seems to be the case for me at least!) then my question is 

'Why do the jars from the local Maven repository also get put on the class-path of the DevMode server?'

Now I don't want to use dev mode, but it'd be nice (as it is there already) to be able to make use of the embedded jetty as just a web server (without gwt-dev on its runtime class-path, and without the local maven jars on its path, and to use the target/XXX-0.0.1-SNAPSHOT as the launcherDir for a code server launcher). That way, I'd be able to have a ready to use solution tied just to a persistable (in a project and hence SCM) Eclipse launcher so (lazy?) people can at least have the option of running this way.... 

Anyway, I am going to have go at making this work (possibly via my own launcher type - I'm not sure yet) so users will then have this option as well as my other generative solution to create a ready to use server/code server combination (the latter still has the single disadvantage that needs a Tomcat installation 'somewhere' - I do realise that it also has many advantages btw!).

As a start, I am looking at the SevletContainerLauncher/Jettylauncher hierarchy..... 
Thomas said:

'to run Jetty in the same way as the default launcher except without the classloader broken tricks'

Do any of you happen to know where in the plug-ins code to find these 'broken tricks' :)? 

If not, then no worries and thanks again for your help......

**Comment by tbroyer** [comment] 2016-11-08 11:33
> It's like the embedded Jetty is using this folder (XXX/target/XXX-0.0.1-SNAPSHOT) as its equivalent to the wtp.deploy folder to 'publish' all of the jars into a war structure... If that is so (and it certainly seems to be the case for me at least!)

GWT (either directly or through the embedded Jetty server) doesn't move JARs around. If something does the copying, it must be Eclipse.

> 'Why do the jars from the local Maven repository also get put on the class-path of the DevMode server?'

Probably because it's impossible to tell which JARs are server-only and which are client-only? Without knowing the details of your setup, it's hard to tell.

> Thomas said:
> 
> 'to run Jetty in the same way as the default launcher except without the classloader broken tricks'
> 
> Do any of you happen to know where in the plug-ins code to find these 'broken tricks' :)?

The whole `WebAppClassLoaderExtension` class: https://github.com/gwtproject/gwt/blob/2.8.0/dev/core/src/com/google/gwt/dev/shell/jetty/JettyLauncher.java#L341-L516
Using the standard Jetty `WebAppClassLoader` should (hopefully) be enough.

**Comment by dfht** [comment] 2016-11-08 11:38
'Do any of you happen to know where in the plug-ins code to find these 'broken tricks''

I'm guessing the WebAppContextWithReload.WebAppClassLoaderExtension..findResource(String name)...
is a good staring point......

**Comment by dfht** [comment] 2016-11-08 11:58
> 'GWT (either directly or through the embedded Jetty server) doesn't move JARs around. If something does the copying, it must be Eclipse.'

As I say, it only happens when running the dev mode launcher though..............I'll try and get to the bottom of that, but I can only tell you at present that it very definitely does happen then, and only then........

> Probably because it's impossible to tell which JARs are server-only and which are client-only? Without knowing the details of your setup, it's hard to tell.

For me I only want to use it as a server, so I guess I don't care.....

> Using the standard Jetty WebAppClassLoader should (hopefully) be enough.

Yes, I've got the source here and that sounds good. I'll give it a try...

Thanks again for your help.

**Comment by tbroyer** [comment] 2016-11-08 12:55
> For me I only want to use it as a server, so I guess I don't care.....

Then just use that? An embedded Jetty server I mean, without even GWT in the equation?
BTW, when using DevMode, that's already what it is (except for the `WebAppClassLoaderExtension`), and uses the `-war` directory as the `-launcherDir` for CodeServer (which simply happens to be run in-process).

If you want to contribute a switch to turn off `WebAppClassLoaderExtension`, I'd be happy to review it. Otherwise, can we close this issue?

**Comment by dfht** [comment] 2016-11-08 13:14
> Then just use that? An embedded Jetty server I mean, without even GWT in the equation?

Yes, that's what I'm looking at right now.... I want to free it from gwt-dev as well to avoid the jar clashes caused by embedded third party stuff. What I want is a ready to use web server that avoids the set-up steps of downloading Tomcat etc. However it's starting to feel like you are right and that it may not be worthwhile :).

> BTW, when using DevMode, that's already what it is (except for the WebAppClassLoaderExtension), and uses the -war directory as the -launcherDir for CodeServer (which simply happens to be run in-process).

Yes I know, but I don't want CodeServer in process as that means gwt-dev on the path!
I tried switching the 'WebAppClassLoaderExtension' (sub-classed JettyLauncher and overrode the 'createWebAppContext' and used the -server argument in my launcher) but it still ran into the issue of having duplicate jars on the class-path. Besides, jettyLauncher is provided from gwt-dev, so that rules it out as a solution to my 'problems'. I would kind of need to divorce the launcher from the Eclipse project class-path entirely and just have it working off of the target/XXX folder and the jars under WEB-INF/lib. 
It's all starting to sound exactly like the set-up of downloading a web server runtime :). I don't want to reinvent the wheel....

Yes, we can close the issue. I don't think there's anything needs doing tbh :). I think I'm realising why it is all as it is and I'm going to settle for just deploying to whatever installed WTP runtimes are present..........

**Comment by dfht** [comment] 2016-11-08 13:26
I think I see part of your point now about separating the server and client only projects. It'd be a big re-organisation for us though right now, but we'll likely have to do it eventually....

**Closed** 2016-11-08 13:59 UTC
