### ISSUE TITLE
The GWT compiler leaves behind some temp files that could otherwise be set to deleteOnExit

### ISSUE THREAD

**Issue by OneGeek** [gwtproject/gwt#9587] opened 2018-01-05 17:30 UTC
**GWT version:**  2.8.2
**Browser (with version):** 
**Operating System:** Windows 7

---

##### Description

The GWT compiler leaves behind some temp files that could otherwise be set to deleteOnExit. Other temp files made by the GWT compiler do set to deleteOnExit and I believe the omission to be unintentional.

The files left behind are the compiler's workDir when unspecified "gwtc99...99.tmp" and css converter files made by the GssResourceGenerator "SOMEUUIDcss_converter99...99.tmp".

##### Steps to reproduce

Run a GWT compile, notice that these files are left behind.

##### Known workarounds

Manually clearing out those temp files.

**Comment by niloc132** [comment] 2018-01-05 17:52
Are you sure they aren't deleteOnExit (I haven't actually checked yet)? From our discussion on gitter, you reported that Eclipse kills the JVM rather than letting it edit gracefully, which would prevent the deleteOnExit functionality from working at all. It might make more sense to file issues against the eclipse plugin to let it own the work, temp dirs, and manually clean them up between devmode launches.

**Comment by OneGeek** [comment] 2018-01-05 19:58
@niloc132 Yeah, I've actually looked for all usages of createTemporaryFile and checked to see if there was a corresponding call to deleteOnExit. Those two were missing one. I've got a patch written, but I'm having some trouble with pushing to gerrit.

**Comment by superbob** [comment] 2019-06-18 10:03
If you look at https://github.com/gwtproject/gwt/commit/7d3b89341b71ac65a4283397b75cebb99e980e56#diff-51ce8685df49ef846c81db454e083b60 in the constructor of DiskCache, you can see that the cleanup mechanism (Shutdown) has been removed in 2.8.x for simplification purposes. This causes a side effect: the gwt*XXX*byte-cache file not to be deleted because the DiskCache is not properly closed at is was done before. This can leave big files on disk (I have seen some 2GB files).

**Comment by tbroyer** [comment] 2019-06-18 11:24
`DiskCache` was made a true singleton in this commit, that's why the shutdown mechanism was removed.
The file is create using `createTempFile` so it's automatically scheduled for deletion when the JVM exits. The only caveat is that the JVM has to exit *cleanly* for the shutdown hooks to run and actually delete the file. Some IDEs (specifically Eclipse) do **not** cleanly shutdown JVMs (i.e. on Linux, they send a SIGKILL rather than SIGTERM), leaving those files behind.

**Comment by superbob** [comment] 2019-06-18 12:42
The problem here is `file = new RandomAccessFile(temp, "rw");`.
The `file` used to be closed in the shutdown hook by the _DiskCache.close_ method in 2.7.
Since 2.8, the _DiskCache.close_ method has been deleted and the _RandomAccessFile_ is not closed anymore.
Even outside of Eclipse, I can reproduce the problem with the following code:

	public static void main(String[] args) throws IOException
	{
		File temp = File.createTempFile("gwt", "byte-cache");
		temp.deleteOnExit();
		RandomAccessFile file = new RandomAccessFile(temp, "rw");
		file.setLength(0);
	}

In the end the temp file is not deleted by the file system.
If you debug the shutdown hook you will see the underlying _File.delete_ method returning _false_ meaning it was not deleted.
If you take the following sample code, it works fine:

	public static void main(String[] args) throws IOException
	{
		File temp = File.createTempFile("gwt", "byte-cache");
		temp.deleteOnExit();
	}

This one works fine too:

	public static void main(String[] args) throws IOException
	{
		File temp = File.createTempFile("gwt", "byte-cache");
		temp.deleteOnExit();
		RandomAccessFile file = new RandomAccessFile(temp, "rw");
		file.setLength(0);
		file.close();
	}

Finally I can confirm that with Eclipse on Windows, when you shutdown the code server (using the X button of the code server window) the _deleteOnExit_ shutdown hook is called.

**Comment by superbob** [comment] 2019-06-18 15:14
If I add

	Runtime.getRuntime().addShutdownHook(new Thread(() -> {
		if (file != null)
		{
			try
			{
				file.close();
			}
			catch (IOException e)
			{
				// It is a shutdown hook
			}
		}
	}));

to the previously non working code, the file gets deleted correctly.

**Comment by rluble** [comment] 2019-06-18 16:45
The RandomAccessFile is using the same file `temp` that should be deleted on exit. However there is  a known [bug](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4171239) in windows, where deleteOnExit does not work on open files. 

Perhaps you could send a patch that adds the following code back
```
  @Override
  protected synchronized void finalize() throws Throwable {
    if (file != null) {
      file.close();
     }
  }
```
With an comment explaining why this is needed (so that it does not get removed again:) I'd be happy to review it.

**Comment by superbob** [comment] 2019-06-19 07:25
There is no guaranty for finalize to be called. In fact, I've run a small test and it is not called in it. Why not using a shutdown hook as before?

**Comment by superbob** [comment] 2019-06-19 09:15
BTW, I've made a patchset : https://gwt-review.googlesource.com/c/gwt/+/21680 using the shutdown hook solution

**Comment by hkdennis2k** [comment] 2019-06-19 15:50
Do you open to use non-JDK APIs and bring in platform specific implementation/behavior?

In many cases, the application has no interested to the file, the path of it on file system to be exact.
In many cases it is more interested to a have shared / out of heap / file system backed temporary byte[] store.

I checked the DiskCache, it seem that the only objective is to have a a out of heap temporary store.

On Linux platforms,  I believe you can delete the file immediately (because it is not locked) just after `new RandomAccessFile` and the kernel should handle the rest like `mkstemp`

On Windows you have different file system design and cannot delete file in use.
But `cleanmgr.exe` should do it's job if we generate the file in the right folder.

Beside, it might be even simpler to just have a 'scan and purge' on application startup to delete old/unused file.

**Comment by rluble** [comment] 2019-06-25 13:30
> There is no guaranty for finalize to be called. In fact, I've run a small test and it is not called in it. Why not using a shutdown hook as before

The old code had both a shutdown hook and finalize. I was wondering if finalize was indeed called when the application exits. Any way shutdown hook it is.

**Comment by rluble** [comment] 2019-06-25 13:31
> Do you open to use non-JDK APIs and bring in platform specific implementation/behavior?

In general no.

**Comment by rluble** [comment] 2019-07-18 18:18
Submitted the fix.

**Closed by rluble** 2019-07-18 18:18 UTC
Labels: Category-Compiler
