### ISSUE TITLE
SDM source mapping does not work reliably on clients others than localhost

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#8910] opened 2015-06-10 20:05 UTC
Originally reported on Google Code with ID 8955
```
using bindAddress 0.0.0.0 allows to access SDM (started up through dev mode) to be accessed
from any host.

Unfortunately SDM uses a full url for source maps. In my case is uses the host name
of my mac, which is not known to the DNS server. For that reason source maps fail to
load and I can only debug JavaScript in chrome dev tools.

Instead of relying on absolute urls for the source maps SDM should use a relative url.
```

Reported by `katharina.fahnenbruck` on 2014-10-19 10:32:54

**Comment by gwtuser** [comment] 2015-07-01 22:23
Please make sure accessing the server machine via IP address is covered by this fix.  I'm hitting the same problem when I try to access the server by IP address who's name is not propagated.  When I open the page on the client machine, it loads fine and the CodeServer on the host runs, but no source maps are available in Chrome.

As a workaround, I've added a binding for the host machine's name/IP in the hosts file of the client machine.  (Of course, this requires administrator/root access on the client.)

**Comment by dsbecker** [comment] 2016-02-03 17:13
@dankurka I see you assigned this issue to yourself.  I am working on a patch for this and https://github.com/gwtproject/gwt/issues/8467 and wanted to check if you already had something pending or not?

**Comment by tbroyer** [comment] 2016-02-03 17:24
I think Daniel self-assigned all issues when he imported them from the old issue tracker at Google Code, so I don't think it means anything special and you can go ahead and work on it.

**Comment by dsbecker** [comment] 2016-02-03 18:41
https://gwt-review.googlesource.com/#/c/14300/

**Comment by tbroyer** [comment] 2016-03-24 15:06
Based on comments above: https://gwt-review.googlesource.com/14556

(I'm tempted to close this is a duplicate of #8467 though)

**Closed** 2016-04-15 08:30 UTC
Labels: Category-SuperDevMode
