### ISSUE TITLE
JsInterop generating null.$_nullMethod() in some cases (when optimization > 0)

### ISSUE THREAD

**Issue by BenDol** [gwtproject/gwt#9345] opened 2016-05-18 06:18 UTC
_Format for this issue used from #9011 since it essentially the same issue._ 

Compiling a jsinterop project with optimizationLevel greater than 0 causes javascript
errors.

`var $gwt_version = "2.8.0-SNAPSHOT";`

1.- Install and compile this project https://github.com/BenDol/jsinterop-issue

2.- Inside the project we have the following code:
```java
    @Override
    public void onModuleLoad() {
        Button button = new Button("Click Me");
        button.getElement().setId("btn1");
        RootPanel.get().add(button);

        $(button).on("click", (e, o) -> {
            Element gwtElement = $(e.getCurrentTarget()).asElement();
            Window.alert(gwtElement.getId());
            return true;
        });
    }
```
This is utilizing the jquery library that I have included in the project.

2.- Checking the output of compilation in `/target/jsinterop-issue-1.0-SNAPSHOT/jsinteropissue` you will be able to find the following:

_this is with optimization enabled_
```javascript
function init(){
  var button;
  // ... snipped ...
  button = new Button;
  ($clinit_DOM() , button.element).id = 'btn1';
  $add_0(($clinit_RootPanel() , get_0()), button);
  $wnd.$(button.element).on('click', makeLambdaFunction(JsInteropIssueEntry$lambda$0$Type.prototype.call_0, new JsInteropIssueEntry$lambda$0$Type));
}

_.call_0 = function call_0(arg0, arg1){
  var gwtElement;
  return gwtElement = $wnd.$(null.$_nullMethod()).get(0) , alert_0(gwtElement.id) , $clinit_Boolean() , $clinit_Boolean() , true;
}
;
```

3.- The generated code without optimization looks like this and works fine:
```javascript
_.onModuleLoad = function onModuleLoad_2(){
  var button;
  button = new Button_0('Click Me');
  $setId(button.getElement(), 'btn1');
  get_2().add_1(button);
  $(button).on('click', makeLambdaFunction(JsInteropIssueEntry$lambda$0$Type.prototype.call_0, new JsInteropIssueEntry$lambda$0$Type));
}

function lambda$0(e_0, o_1){
  $clinit_JsInteropIssueEntry();
  var gwtElement;
  {
    gwtElement = $asElement($wnd.$(e_0.currentTarget));
    alert_0($getId(gwtElement));
    return valueOf_3(true);
  }
}
```

**Comment by tbroyer** [comment] 2016-05-18 08:40
```
@JsType(name = "jQuery")
public class Event
```

The type is not `isNative=true`, so unless you export it, because it's never instantiated, it's optimized out.

This is a dupe of #9330

**Closed by tbroyer** 2016-05-18 08:40 UTC
Labels: Category-Compiler
