### ISSUE TITLE
"Internal compiler error" when compiling certain lambdas

### ISSUE THREAD

**Issue by Leonya** [gwtproject/gwt#9174] opened 2015-08-11 11:19 UTC
I am trying to move my project to use GWT 2.8-SNAPSHOT since I've seen mentions of lambda support being production-ready. However, after doing a bulk conversion of the codebase to use lambdas (by means of an IntelliJ IDEA refactoring), I am getting compilation errors. I have managed to identify a problematic piece of code precisely (unnecessary details omitted):

```
public Widget getView(final GwtDiscussion discussion, @NotNull final ViewModel dataStore) {
  final SimpleSignal<Boolean> isActive = Signals.constant(true);

  return ViewBuilder
    .builder(lifetime, "discussion", dataStore)
    .onClick(event -> activeDiscussion.set(Boolean.TRUE.equals(isActive.current()) ? null : discussion))
    .build();
}
```

The compiler error is the following:

```
Information:Using javac 1.8.0_51 to compile java sources
Information:Skipping ant target "after.compilation" because of compilation errors
Information:8/11/15, 1:08 PM - Compilation completed with 34 errors and 0 warnings in 10s 382ms
Error:GWT Compiler: Unexpected internal compiler error
Error:GWT Compiler: at com.google.gwt.thirdparty.guava.common.base.Absent.get(Absent.java:47)
Error:GWT Compiler: at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.replaceLambdaWithInnerClassAllocation(GwtAstBuilder.java:1391)
Error:GWT Compiler: at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.endVisit(GwtAstBuilder.java:1258)
Error:GWT Compiler: at org.eclipse.jdt.internal.compiler.ast.LambdaExpression.traverse(LambdaExpression.java:689)
Error:GWT Compiler: at org.eclipse.jdt.internal.compiler.ast.MessageSend.traverse(MessageSend.java:1031)
Error:GWT Compiler: at org.eclipse.jdt.internal.compiler.ast.MessageSend.traverse(MessageSend.java:1022)
Error:GWT Compiler: at org.eclipse.jdt.internal.compiler.ast.ReturnStatement.traverse(ReturnStatement.java:380)
Error:GWT Compiler: at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.traverse(MethodDeclaration.java:355)
Error:GWT Compiler: at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1415)
Error:GWT Compiler: at org.eclipse.jdt.internal.compiler.ast.QualifiedAllocationExpression.traverse(QualifiedAllocationExpression.java:609)
Error:GWT Compiler: at org.eclipse.jdt.internal.compiler.ast.ConstructorDeclaration.traverse(ConstructorDeclaration.java:625)
Error:GWT Compiler: at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1360)
Error:GWT Compiler: at com.google.gwt.dev.jjs.impl.GwtAstBuilder.processImpl(GwtAstBuilder.java:3825)
Error:GWT Compiler: at com.google.gwt.dev.jjs.impl.GwtAstBuilder.process(GwtAstBuilder.java:3856)
Error:GWT Compiler: at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater$UnitProcessorImpl.process(CompilationStateBuilder.java:129)
Error:GWT Compiler: at com.google.gwt.dev.javac.JdtCompiler$CompilerImpl.process(JdtCompiler.java:383)
Error:GWT Compiler: at org.eclipse.jdt.internal.compiler.Compiler.processCompiledUnits(Compiler.java:488)
Error:GWT Compiler: at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:453)
Error:GWT Compiler: at com.google.gwt.dev.javac.JdtCompiler.doCompile(JdtCompiler.java:1017)
Error:GWT Compiler: at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater.compile(CompilationStateBuilder.java:325)
Error:GWT Compiler: at com.google.gwt.dev.javac.CompilationStateBuilder.doBuildFrom(CompilationStateBuilder.java:548)
Error:GWT Compiler: at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:479)
Error:GWT Compiler: at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:465)
Error:GWT Compiler: at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:423)
Error:GWT Compiler: at com.google.gwt.dev.Precompile.precompile(Precompile.java:222)
Error:GWT Compiler: at com.google.gwt.dev.Precompile.precompile(Precompile.java:202)
Error:GWT Compiler: at com.google.gwt.dev.Precompile.precompile(Precompile.java:143)
Error:GWT Compiler: at com.google.gwt.dev.Compiler.run(Compiler.java:197)
Error:GWT Compiler: at com.google.gwt.dev.Compiler.run(Compiler.java:156)
Error:GWT Compiler: at com.google.gwt.dev.Compiler$1.run(Compiler.java:117)
Error:GWT Compiler: at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
Error:GWT Compiler: at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
Error:GWT Compiler: at com.google.gwt.dev.Compiler.main(Compiler.java:124)
```

I am using a snapshot build from the 5th of August.

**Comment by branflake2267** [comment] 2015-08-11 14:59
What version of guava are you using?

**Comment by Leonya** [comment] 2015-08-11 15:13
Guava 18.

**Comment by branflake2267** [comment] 2015-08-11 17:44
I think Guava 19 is out, could you try that?

**Comment by jnehlmeier** [comment] 2015-08-11 18:00
@branflake2267 it's not a Guava issue. It's most likely a bug in `GwtAstBuilder$AstVisitor.replaceLambdaWithInnerClassAllocation()`.

@Leonya Is your code somehow used inside anonymous local classes? If yes then your issue might be related to https://gwt-review.googlesource.com/#/c/13340/

**Comment by Leonya** [comment] 2015-08-12 08:56
> Is your code somehow used inside anonymous local classes?

Yes, it is. Great there's a PR already, hope it lands soon!

**Comment by Leonya** [comment] 2015-08-13 17:10
I can confirm that commit 7129828214a32d0f3d386329acdd197be8dc505a fixes this particular compilation failure.

**Comment by tbroyer** [comment] 2015-08-13 19:53
Dupe of #8991

**Closed by tbroyer** 2015-08-13 19:53 UTC
