### ISSUE TITLE
JSP error with GWT 2.8 RC2

### ISSUE THREAD

**Issue by xRomZak** [gwtproject/gwt#9396] opened 2016-08-12 15:07 UTC
There is an exception when I try to compile and to deploy my application in SuperDevMode using GWT 2.8 RC2. But both dev modes work perfectly with GWT 2.8 beta1  (Jetty 8.x). 
There are no new libs and dependencies in deployment, just a test with the latest GWT version.

`org.apache.jasper.JasperException: java.lang.ClassCastException: org.apache.tomcat.SimpleInstanceManager cannot be cast to org.apache.tomcat.InstanceManager
	at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:585)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:396)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:405)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:349)
	at org.eclipse.jetty.jsp.JettyJspServlet.service(JettyJspServlet.java:107)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:66)

**Comment by wlsc** [comment] 2016-08-13 08:57
It also happens sometimes when the memory demand of your application is more than your Jetty server environment offers to your applications. Could you check your memory settings for server as well as for application?

**Comment by tbroyer** [comment] 2016-08-13 12:24
```
org.apache.jasper.JasperException: java.lang.ClassCastException: org.apache.tomcat.SimpleInstanceManager cannot be cast to org.apache.tomcat.InstanceManager
```

This hints at a cross-classloader issue. What JARs do you have in `WEB-INF/lib`? Also, is this with the GWT SDK or with dependencies coming from the Central repository?

**Comment by xRomZak** [comment] 2016-08-13 18:30
There is no repository. Project is compiled by Ant using downloaded GWT SDK and a set of libs.
Content of WEB-INF/lib:
aopalliance.jar
buji-pac4j-core-1.4.3.jar
buji-pac4j-servlet-1.4.3.jar
cas-client-core-3.4.1.jar
commons-lang-2.6.jar
commons-lang3-3.4.jar
commons-net-3.4.jar
guava-18.0.jar
guice-3.0.jar
guice-assistedinject-3.0.jar
guice-jndi-3.0.jar
guice-multibindings-3.0.jar
guice-servlet-3.0.jar
guice-throwingproviders-3.0.jar
gwt-i18n-server-0.23.jar
httpclient-3.1.jar
jackson-annotations-2.6.6.jar
jackson-core-2.6.6.jar
jackson-databind-2.6.6.jar
jackson-dataformat-xml-2.6.6.jar
jackson-jaxrs-base-2.6.6.jar
jackson-jaxrs-json-provider-2.6.6.jar
jackson-module-jaxb-annotations-2.6.6.jar
jersey-apache-client-1.19.1.jar
jersey-client-1.19.1.jar
jersey-core-1.19.1.jar
jersey-guice-1.19.1.jar
jersey-json-1.19.1.jar
jersey-server-1.19.1.jar
jersey-servlet-1.19.1.jar
json-20080701.jar
jsr305-1.3.9.jar
jsr311-api-1.1.1.jar
pac4j-cas-1.8.9.jar
pac4j-core-1.8.9.jar
quartz-2.2.3.jar
shiro-core-1.2.5.jar
shiro-guice-1.2.5.jar
shiro-web-1.2.5.jar
stax2-api-4.0.0.jar
urlrewritefilter-4.0.4.jar
woodstox-core-asl-4.4.1.jar

**Comment by branflake2267** [comment] 2016-08-15 17:02
`org.apache.jasper.JasperException: java.lang.ClassCastException:  shouldn't be in the launcher classpath. This happens when the build system configures the class path. I've seen this in m2e when the gwt-user and other libs get added to the WEB-INF/libs directory. I suspect you can manually remove the libraries from the SDM launcher and it should fix it.

**Comment by TheBojda** [comment] 2016-08-22 20:02
I've the same problem with GWT 2.8-rc2. If I use the same project with GWT 2.7, jsps work fine.

**Comment by tbroyer** [comment] 2016-08-23 13:03
I can't reproduce (with the following steps). Can you share a repro case?

Here's what I tried:
```
$ mvn archetype:generate \
    -DarchetypeCatalog=https://oss.sonatype.org/content/repositories/snapshots/ \
    -DarchetypeGroupId=net.ltgt.gwt.archetypes \
    -DarchetypeArtifactId=modular-webapp \
    -DarchetypeVersion=1.0-SNAPSHOT
…
Confirm properties configuration:
groupId: test
artifactId: app
version: 1.0-SNAPSHOT
package: test.app
module: App
module-short-name: testapp
 Y: : 
…
$ cd app
$ mv app-server/src/main/webapp/index.html app-server/src/main/webapp/index.jsp
$ vim app-server/src/main/webapp/index.jsp
# add <%= new java.util.Date().toString() %> somewhere in the page
$ vim pom.xml
# add <warDir>app-server/target/app-server-${project.version}</warDir> to the gwt-maven-plugin next to the existing <launcherDir> line
$ mvn package -Dgwt.skipCompilation
$ mvn gwt:devmode
```
Opening `http://localhost:8888/index.jsp` works without problem, compiling the JSP and displaying the current date.

I also tried the same but using gwt-user.jar, gwt-dev.jar and gwt-servlet.jar from the GWT SDK (more accurately, a local build from the 2.8.0-rc2 tag; using `<scope>system</scope><systemPath>…</systemPath>` in Maven) and it works the same.

So it really must have something to do with dependencies in `WEB-INF/lib` and/or in the classpath.

Anyway, JSP support is only provided as a "best effort", and you're encouraged to use a separate server rather than DevMode's embedded Jetty server.

**Comment by TheBojda** [comment] 2016-08-23 20:43
I'm using Google Plugin for Eclipse and Web Application Project. When I run it by Run in Super Dev mode and try http://localhost:8888/index.jsp, it throws the error.

**Comment by tbroyer** [comment] 2016-08-24 13:44
@branflake2267 Could you do a simple check in Eclipse? I doubt you'd have different results as I got with Maven (and knowing how it launches GWT DevMode) but just in case. Then we can probably close this issue (move the discussion to the forum, or even possibly StackOverflow).

To people facing this issue: again, please provide a repro case.

**Comment by branflake2267** [comment] 2016-08-24 15:20
I only noticed the exception above when the gwt-dev was getting added to the server classpath which m2e configurator was doing b/c the gwt jars were not scoped as provided. I use Eclipse daily and haven't seen the issue. Are you asking me to run the scenario above?

**Comment by tbroyer** [comment] 2016-08-24 16:12
By _server classpath_ you mean copied to `WEB-INF/lib`?

(and yes, I was asking you to run the scenario :wink: : create a simple GWT app –probably through the Google Plugin for Eclipse wizard, I don't what's needed to use the "Web Application Project", I don't even know what it actually is), put a simple JSP in it, run it in SDM and open `http://localhost:8888/index.jsp`; but if you say JSPs work inside the DevMode embedded server in other projects that do **not** use Maven, then it's enough confirmation for me)

**Comment by branflake2267** [comment] 2016-08-24 16:14
Yes: WEB-INF/lib was what I was referring to as the server classpath. I think jetty gets boggled up when gwt-dev gets in there with the newer jetty stuff. I suppose I could fix this in Eclipse by upgrading jetty or something else related to that. 

I'll check out the test case shortly.

**Comment by branflake2267** [comment] 2016-08-24 16:34
I never tried this out. I like the layout. So this won't work with the standard dev mode configuration b/c m2e doesn't know how to setup a war directory in another module, at least not yet. By the way, I'm using the GPE fork, GWT Eclipse Plugin. I did wire up the m2e configurator to import your project. And I think I have to fix it when the module name is different. 

![screen shot 2016-08-24 at 9 26 56 am](https://cloud.githubusercontent.com/assets/1326504/17938953/17d34ca8-69dd-11e6-95e1-1872d056849e.png)

That said, I haven't tried it yet, but looks like a perfect scenario for a WTP server runtime configuration. So instead of using the built in jetty server, I'd suggest setting up a Eclipse server runtime, tomcat, jetty, or any external server for that matter. Even running it from Maven works fine. And then use the CodeServer launcher to launch SDM process. If you do use a server runtime, the CodeServer should start automatically. I think I'll call this server first approach, b/c the web server really is the most important piece to me. Then comes the GWT debugger which puts some more bits into that server container. (I have some videos that show this approach for those who are reading and haven't seen the config.) 

On another note, looks like something has to be done with Eclipse wiring to help out with this.

**Comment by branflake2267** [comment] 2016-08-24 17:01
Follow up. I've tested using a server runtime. Eclipse will start up a server to host the project just fine. I tested it with the Tomcat server runtime b/c it's so easy to get and setup. But for some reason, I can't start the code server launcher. It looks like m2e is not picking up the lifecycle wiring and running it, which generates the module into the classpath. I've marked these as high priority issues to fix asap.

**Comment by tbroyer** [comment] 2016-08-24 17:07
Sorry, it looks like I made you waste time on something I didn't meant to: what I really meant was to create a small non-Maven project in Eclipse and try to reproduce there, doing everything from Eclipse, with no other build tool.

Anyway, as no one provided any repro case or repro steps and I can't reproduce the issue, let's close this. We can revisit if someone can make us reproduce the issue and it really is a bug in GWT (rather than a misuse)

**Closed by tbroyer** 2016-08-24 17:07 UTC

**Comment by branflake2267** [comment] 2016-08-24 19:24
No worries, it's good for me test stuff out. I still need to perfect m2e configuring using your plugin.

**Comment by mark-webworks** [comment] 2016-09-04 12:23
Same issue (and workaround): https://plus.google.com/+MarkSederqvist/posts/2xjnLm4Frr3
