### ISSUE TITLE
Class incorrectly placed in left-over code fragment because of Static Code analyzer code replacement

### ISSUE THREAD

**Issue by edbras** [gwtproject/gwt#9194] opened 2015-09-22 21:27 UTC
++ Gwt version: 2.7.0
++ Forum post: https://groups.google.com/forum/#!topic/google-web-toolkit/QFASkgkg-ps (especially the last part)
I have a LoginControllerDefault that is exclusive in a split point X, but still placed in the left-over fragment by the GWT compiler.

This is because the interface LoginController is replaced by the only implementing class LoginControllerDefault during the Static code analyzer that runs before processing the split points. 
As such, during the processing of the split point the LoginControllerDefault is seen by several code fragments that use the LoginController such that it's placed in the left-over fragment.

++ I confirmed this by overcoming that the Static Code analyzer replaced the LoginController with the LoginControllerDefault:
I  created an additional LoginControllerDummy class that implements the LoginController interface.  The creation of the LoginControllerDefault or LoginControllerDummy depends on the property in the index.html that is read through a GWT Dictionary instance. As such that the the Static Code analyzer doesn't know that the LoginControllerDefault is the only one that will be used, as such that  it will not replace the LoginController with the LoginControllerDefault.

After doing this, the LoginControllerDefault was removed from the left-over fragment and only present in an exclusive code fragment. The left-over size was reduced with about 100K :) It will probably reduce more as I will use the same trick with other classes.

++Test case: sorry, don't have this, but after reading the above, I don't think it's needed. you could also use the test case used in issue "https://github.com/gwtproject/gwt/issues/7871" after adding the above interface/class construction.

I hope this will be solved soon, as it can really reduce the left-over a lot, and as such reduce the startup of the application significant.... (my experience)

**Comment by edbras** [comment] 2015-09-24 22:28
During implementing the workaround, I noticed the following:
+ The impact is big. I have made additional subclasses for all my controller implementation classes that are created in a split point and noticed already a reduce in left-over from 779KB to 609KB.  And I am not finished yet, as I noticed that I have to do the same with additional interfaces like View's used in the Controller interface. I think you can get reductions around 30%, which is a lot and will result in a much less start up time of your app.

+ I noticed it has annoying side corners due to the same bug. For example: I noticed that my ProfileControllerDefault was still alive in the left-over, which was due to some shared class used by 2 split points of which one was in which the ProfileControllerDefault is created. However, the shared class contains a Listener interface that is only implemented by ProfileControllerDefault, as such that it's replaced by the ProfileControllerDefault and as such seen from they other split point :(... Very annoying, and it costs a lot of time.  
BTW: I solved it by letting the other class that also uses the shared class, also implements the same Interface, such that the ProfileControllerDefault wasn't the only implementing class anymore, and automatically disappeared from the other split point and become exclusive to it's own split point, and as such not end up in the left-over anymore...
 
I hope more people experience the same problem, such that they vote this issue and it will be solved soon. The workaround work, but it's a lot of coding and doesn't really make the code maintainable. ....

**Comment by jnehlmeier** [comment] 2015-09-25 01:06
You should check the actual transferred file size in the browser when using gzip compression. Maybe its simply not worth it adding all the workarounds in your code if gzip compression changes your expected 30% size reduction to just a 5% reduction.

**Comment by edbras** [comment] 2015-09-25 08:03
I am using gzip compression, and I think it's hard to predict the actual reduction/change, especially because split points might be merged when getting very small, such that it saves a http roundtrip and 5% on a desktop might be a lot on a mobile with a weak connection.

**Comment by cromwellian** [comment] 2015-10-06 05:29
Try a build newer than last Friday. We fixed one code splitter issue and it
may help

**Comment by edbras** [comment] 2015-10-07 14:38
Thanks ray, I will sure ...

**Comment by rluble** [comment] 2016-05-31 06:37
Code splitting happens after optimization and the optimizations passes for the most part optimize independently of whether how the code would be later split. 

This is working as intended. The solution for these cases is to have a second implementor of the interface that is live.

**Closed by rluble** 2016-05-31 06:37 UTC

**Comment by edbras** [comment] 2016-05-31 10:18
> This is working as intended. 
Please change the intended behavior?
Then I don't think this is correct as it's not what developers expect.
 
>The solution for these cases is to have a second implementor of the interface that is live.
This is a workaround and not a very good solution.
How will this be solved in the future?

**Comment by rluble** [comment] 2016-05-31 15:12
Maybe it was poorly phrased, the issue is a product of the current design. AFAIK there are no specific plans to redesign the optimization pipeline to address this codesplitter issue, but it is an open source project and of course contributions are always welcome.
