### ISSUE TITLE
"Failed to write Core Dumps while GWT compilation"

### ISSUE THREAD

**Issue by AnanthaBhople** [gwtproject/gwt#9217] opened 2015-11-16 10:08 UTC
Hi Friends ...Please help me

"I am facing following problem while GWT compilation"

A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000005cc5d158, pid=4732, tid=3032
#
# JRE version: Java(TM) SE Runtime Environment (7.0_75-b13) (build 1.7.0_75-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (24.75-b04 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# V  [jvm.dll+0x49d158]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.sun.com/bugreport/crash.jsp

**Comment by dankurka** [comment] 2016-05-15 08:48
Since the GWT compiler does not load any native code by itself, this is probably not caused by us. Closing off.

**Closed by dankurka** 2016-05-15 08:48 UTC
