### ISSUE TITLE
Update jetty-9.2.14.v20151106 in gwt-dev to more recent version 9.4+

### ISSUE THREAD

**Issue by slavap** [gwtproject/gwt#9606] opened 2018-03-30 00:27 UTC
In dev mode under Eclipse I'm running my server side code on embedded jetty, and started getting errors related to newer (Java9 adapted) jars parsing. It would be nice to get jetty updated in upcoming GWT 2.9 release. As workaround -noserver debug setup could be used.

![image](https://user-images.githubusercontent.com/4129763/38119396-52cb3e2e-3376-11e8-8493-1c403c5d19e5.png)

```
The code server is ready at http://127.0.0.1:9876/
Code server started in 8.442 s ms
16:43:46.918 INFO jetty-9.2.14.v20151106 (org.eclipse.jetty.server.Server:327)
[WARN] Server class 'org.springframework.web.SpringServletContainerInitializer' could not be found in the web app, but was found on the system classpath
[WARN] Adding classpath entry 'file:/C:/Users/slavap/.m2/repository/org/springframework/spring-web/4.3.12.RELEASE/spring-web-4.3.12.RELEASE.jar' to the web app classpath for this session
Starting Jetty on port 8888
[WARN] Failed startup of context c.g.g.d.s.j.WebAppContextWithReload@2ad63952{/,file:/C:/Users/slavap/myproj/,STARTING}{C:\Users\slavap\myproj}
java.lang.RuntimeException: Error scanning entry module-info.class from jar file:/C:/Users/slavap/myproj/WEB-INF/lib/javax.json.bind-api-1.0.jar
at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:913)
at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:831)
at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:548)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by niloc132** [comment] 2018-03-30 00:31
(carrying over more discussion from gitter) We'd want to be careful in making this change to not require a newer version of Java. In theory we can use the newest version of jetty which still can support Java 1.7, or have the separate discussion of moving to a baseline of Java 8.

**Comment by jnehlmeier** [comment] 2018-03-31 09:09
Looks like the issue is only fixed in Jetty 9.4.x by ignoring module-info.class files during annotation scanning. So GWT has to back port the fix or require Java 8 for development.

**Comment by mgrue** [comment] 2018-07-04 14:44
Is this issue gonna be taken up for the next release?

**Comment by jnehlmeier** [comment] 2018-07-04 15:29
@mgrue nobody is working on it, so probably not. It is generally recommend to use your own server and not depend on the embedded Jetty of GWT DevMode. You should use `CodeServer -launcherDir ./path/to/exploded/war` instead of DevMode and then deploy that exploded war to a server of your choice.

**Comment by slavap** [comment] 2018-07-05 09:22
That’s sad, even though quite understandable.

**Comment by axls** [comment] 2019-04-17 09:12
@niloc132 @jnehlmeier Does it make sense to start working on a patch with jetty upgrade to 9.4.x? Will the patch be potentially accepted?

**Comment by jnehlmeier** [comment] 2019-04-18 19:10
@axls It won't be accepted as long as GWT supports Java 7 because Jetty 9.4.x requires Java 8. 

Would be great if the steering group would decide on:
1. a policy for the minimal Java version required by GWT.
2. wether or not we actually want to maintain Jetty as a feature of GWT SDK. For GWTTestCase and CodeServer it could become an implementation detail. 

If we bump minimal Java version we might need to drop classic DevMode, don't know if it works with Java8+.

**Comment by slavap** [comment] 2019-04-18 20:56
@jnehlmeier Classic DevMode is deprecated for very long time already, and plugin needed for it does not work in any modern browser (the last one where it works was Firefox 24). Also even Java8 is getting "old", and Oracle asking money for continue its support, so Java7 sounds like a joke.

**Comment by tbroyer** [comment] 2019-04-18 22:07
@slavap OpenJDK 7 is still updated (for one more year), and OpenJDK 8 'til 2023: https://access.redhat.com/articles/1299013

My personal opinion: kill legacy DevMode, kill JDK 7 support (particularly for development, gwt-servlet might still support it if there's demand). I would also kill the embedded server in DevMode, or at least its support for webapps (only serve static files).
That's something to be discussed in gwt-contrib though.

**Comment by slavap** [comment] 2019-04-19 00:18
@tbroyer I would say "kill the embedded server in DevMode" is not very good idea. Though it's not very right usage, it's good for quick starting, especially for GWT newcomers, because setup of dedicated Tomcat(or other server) is not that trivial.

**Comment by realityforge** [comment] 2019-04-19 00:30
From a consumers perspective I agree with @tbroyer ;)

**Comment by mdavis95** [comment] 2019-04-19 19:17
+1 to @tbroyer's comments

**Comment by tbroyer** [comment] 2019-04-19 21:25
@slavap How does anyone start a new non-GWT Java web project? And with CORS one could start DevMode serving only static files and make requests to a separate server for Web APIs. How do people do in non-GWT projects involving JS? DevMode could also possibly reverse-proxy to another server (see https://github.com/tbroyer/gwt-devserver). I've been doing React with Webpack or Parcel for some time, and those kinds of setup work quite well in my experience (granted, I'm not a beginner)

**Comment by mdavis95** [comment] 2019-04-19 22:01
Our company works on a gradle plugin that allows "modern" gwt development.  We use gwt-devserver (thanks @tbroyer) as a proxy in front of webpack.  Webpack proxies the rest services, serves the static files, and handles the js dependencies.   We use webpack with gwtbootstrap3 with both gwt-rpc and autorest and as well as with vue-gwt with autorest.

See https://github.com/ascendtech/gwt-gradle and https://github.com/ascendtech/gwt-examples

We are working on ironing out some rough edges and adding features (such as transitive npm and static files dependencies between gradle projects) but we use it in production currently with a few large projects.

We are currently using Java 11 everywhere and only plan to support Java 11+ with the plugin.  I totally can understand GWT wanting to support Java 8 but Java 7 support seems insane especially at the expensive of supporting java 9+ jars with modules.

**Comment by mdavis95** [comment] 2019-04-19 22:08
As a side note we spent months upgrading our large code base with multiple GWT projects from Java 8 to Java 11 and ended up having to switch from GWT-RPC to Autorest to get around this problem.  Java 9 module-info files were coming in from the backend dependencies and splitting out REST services fixed this problem for us but it was a ton of work on a large code base with 100s of GWT-RPC calls that needed to be switched.

**Comment by slavap** [comment] 2019-04-19 22:14
@tbroyer I'm not saying it's impossible to setup, but making GWT working with Eclipse and WTP Tomcat is not that simple comparing to using gwt-dev jetty (that's especially important for newcomers just playing with demos).

**Comment by tbroyer** [comment] 2019-04-20 05:52
@slavap Maven or Gradle to the rescue! Nothing to setup, grab the sample and start playing with it.

**Comment by slavap** [comment] 2019-04-20 08:05
@tbroyer code navigation? Debugging?

**Comment by axls** [comment] 2019-04-22 08:09
@jnehlmeier @tbroyer Thanks for clarifications. So, there are no reasons to upgrade jetty at now (due to java7 support or willing to restrict/remove/replace jetty at all). But what about small fixes related to Jetty 9.4+ compatibility and backward compatible with Jetty 9.2 of course (e.g. https://github.com/gwtproject/gwt/issues/9457)? Could they be accepted?

**Comment by jnehlmeier** [comment] 2019-04-23 19:51
@axls I think you better open (or resurrect) a discussion in gwt-contrib first. Otherwise your work might be wasted time, if we decide to change DevMode. 

What is the concrete issue you run into with Jetty 9.2 dependency? Usually these kind of issues are the result of having client/server code and thus their dependencies in the same project, as in #9457 .

**Comment by slavap** [comment] 2019-04-23 22:27
@jnehlmeier All this situation is really puzzling me. Upgrading to 9.4+ and Java8 is the right thing for GWT 2.9, and effort should not be very big. Later on in GWT3 it all will be quite different anyway, so most of this code will be eliminated for sure. You have developer who is willing/ready to do this upgrade, why not give him green light and support his effort?

**Comment by axls** [comment] 2019-04-24 12:02
@jnehlmeier 

> What is the concrete issue you run into with Jetty 9.2 dependency? Usually these kind of issues are the result of having client/server code and thus their dependencies in the same project, as in #9457 .

Yes, the issue is due to mixing client/server code. I know, it is not recommended, but I found that it is more covenient for development to place code, that usually modified together (my case), in the same project and package.

**Comment by tbroyer** [comment] 2019-04-25 16:43
Fwiw, wrt updating the baseline to JDK 8: https://groups.google.com/d/topic/google-web-toolkit-contributors/tMR3Dv1YBBE/discussion

**Comment by RobertoUa** [comment] 2019-09-11 14:55
Guys, how can I do this myself? I want to fork it and bump jetty version but I couldn't find a place in code where I can do it. This is a blocker for me. Thanks.

(sorry for the offtopic, I will remove the comment once I figure this out)

**Comment by mihaisdm** [comment] 2019-10-22 15:59
Hi,

If anyone still interested, you can find experimental jetty 9.4 :
 https://github.com/mihaisdm/gwt
 https://github.com/mihaisdm/tools

BR
Mihai

**Comment by zhivko** [comment] 2019-11-14 09:23
@mihaisdm your repos support jetty9.4 - I can confirm it is working for me.
https://github.com/mihaisdm/gwt
https://github.com/mihaisdm/tools

**Comment by jkoorts** [comment] 2020-03-06 08:44
@mihaisdm Your 9.4 change is incomplete/dirty See gwt/maven/README.txt. Still some 9.2 mentions.

What I want to do is mvn clean deploy and have it create the jars and poms and drop it in my nexus repo. I'm using intellij and maven.

**Comment by eliasbalasis** [comment] 2020-06-14 19:14
I am sorry to say but it all sounds very awkward and totally inconvenient.

It sounds like the recommended practice is not to use Jetty.

What is the point of supporting Jetty in GWT tools if support for it is broken in GWT core itself?
Shouldn't the two efforts be aligned?

Of course I will choose to run a custom server for production environments or other but during development with GWT tools it is preferable and much more convenient to use Jetty instead.

Please correct me if I have misunderstood.

**Comment by eliasbalasis** [comment] 2020-06-14 19:50
Correction, I didn't mean to say that GWT SDK is broken, it is just the Jetty dependencies that it is built against are not working at runtime.

The problem appears while running SuperDevMode under GWT Eclipse Plugin due to Jetty dependencies misalignment it seems. I am getting all sorts of imcompatibility errors.

It is definitely inconvenient having to run a custom server during development instead of the embedded Jetty and at least for GWT 2.9, unlike 2.8.2, I haven't been able to figure out a custom combination of Jetty and other dependencies that works.

I am practically stuck with GWT 2.8.2.

I hope this is a better explanation of my problem.

**Comment by stezadov** [comment] 2020-06-15 21:04
@tbroyer 
> My personal opinion: kill legacy DevMode, kill JDK 7 support (particularly for development, gwt-servlet might still support it if there's demand). I would also kill the embedded server in DevMode, or at least its support for webapps (only serve static files).

It's understandable why there is a motivation to go away from embedded Jetty. However personally for me deprecating classic dev mode years ago was nothing less than tragedy. Seriously. 
I agree super dev mode has some advantages but guys, JS debugging is not any close to what JDWP provides even now 6 years later. I cherish FF-26 on my system and still do classic dev mode on daily basis. And hope to continue until it gets impossible by any means. Classic dev mode used to be one of the biggest advantages of GWT. Would you please don't kill it?

Similarly it's unfortunate that projects using ASM and dev mode with embedded Jetty (like I do) can't upgrade to 2.9 straight away without switching to external server setup.

**Comment by tbroyer** [comment] 2020-06-15 21:55
Wrt legacy devmode, please remember that browsers broke it. It was deprecated in GWT because as soon as you have a good-enough and future-proof replacement, maintaining a broken tool that also behaves differently from your production code (by design!) becomes a burden.

The embedded webapp server also has many downsides, and only few upsides. I'd be ok to keep the webapp server, if cleanly separating classloaders the way a standard webapp server does. That would probably fix your ASM issue, but even that would break the workflow for many people (there was pushback when I first tried this change a few years ago).
Also, having such a feature, people want it to also support JSPs, JSF, configurable authentication, resource injection, JMS, a newer version, etc. It never ends.

Removing it would also free us from all this maintenance burden.

**Comment by stezadov** [comment] 2020-06-16 08:38
That makes perfect sense. I just would like to vocal that still there is a demand for the classic dev mode and here's why: for the relatively big applications with massive client side logic it gets more important to have a tool to work with that logic rather than the UI bells and whistles. To polish the bells and whistles we could use pretty compile and JS debugger long before the super dev mode was made. Yes super dev mode is better than that but not that colossally. The real power of GWT used to be in that it ran on JVM and thus allowed to polish the client side logic in almost real Java (yes with restricted Java standard API emulation but still enough). This was one of the super justifications to use GWT in the first place and tolerate long compilations of GWT compiler.
I perfectly understand the industry moved to source maps and GWT went along that stream. But IMHO super dev mode is not an adequate replacement for classic dev mode, it's just a nice addition to it.

**Comment by dnouls** [comment] 2020-06-16 08:46
I don’t really have that much problems with SDM. But I try to use as much unit testing as possible, so I barely need to use the sourcemap debugging. I mostly debug in IntelliJ using unit tests.

The one thing that bothers me most is that putting breakpoints does not work well with lambdas. Sometimes I need to rewrite a lambda into an anonymous inner class to be able to put a breakpoint.
Debugging stream API’s is also hard since it mostly depends on lambdas.

Is the lambda support a limitation of source maps or is it a GWTC issue ? In JavaScript and TypeScript they use lambda’s extensively, so why can’t we have decent support for our java debugging ?

**Comment by jnehlmeier** [comment] 2020-06-16 09:43
>The one thing that bothers me most is that putting breakpoints does not work well with lambdas. Sometimes I need to rewrite a lambda into an anonymous inner class to be able to put a breakpoint. Debugging stream API’s is also hard since it mostly depends on lambdas. Is the lambda support a limitation of source maps or is it a GWTC issue ?

@dnouls It might be a SDM / GWTC issue. There are some rare bugs in SDM in which incremental compilation does not pick up added lambdas or changes in lambdas resulting in runtime exception. There is also a source maps bug somewhere which causes server side deobfuscated exceptions (using deployed source maps) showing some nonsense stack frames within an otherwise good stack trace. I wouldn't be surprised is this also happens in SDM and might cause the browser to think that you can not put a break point at a specific "Java" location since no matching JS code exists for it.

@stezadov Maybe you are lucky, but back in the days I have seen numerous JS bugs in the final GWT output which did not happen within classic DevMode because DevMode did use the Java classes directly. Also mobile development is nearly impossible with classic DevMode (but granted, once your app reaches a certain size, it is also impossible with SDM given the large JS output size). Debugging works generally fine for me, using breakpoints, conditional breakpoints and log breakpoints. Given JS is single threaded there isn't really anything more I need to debug issues in our 500 KLOC app in the past years. Just make sure to start SDM using `-style PRETTY -XmethodNameDisplayMode ABBREVIATED` so you can also quickly understand the JS if needed.

**Comment by stezadov** [comment] 2020-06-16 10:09
@jnehlmeier, I wasn't so lucky and did struggle with JS issues, most often browser specific and when it was Safari-specific or even IE-specific it was especially fun given that I work on Linux. So SDM - good, it has its niche. But if I spent half a year in total on the JS issues then I spent another 12 years working on non JS-related client side stuff. Hence my reasoning. 
I admit SDM got better compared to what it was 6 year ago. Idea Ultimate (not Community though) or SDBG in Eclipse or Chrome Connector for NetBeans make it possible to debug it in the IDE (which is really important as navigating/searching the source mapped Java code in browser dev tools is ridiculous). However the source maps support is still buggy in browsers, some of them leaking memory, some hanging, some consuming too much memory, etc. Overall it's way worse than the old and proved JDWP debuggers every Java developer is used to.
Yes browser debugger has some advantages like DOM breakpoints and etc. But I simply don't need it most of the time. And even when I need it I also can do it in web mode with pretty compilation, so SDM ease things but not more than that.

**Comment by eliasbalasis** [comment] 2020-06-16 10:28
@stezadov , I couldn't agree more regarding use of JDWP debuggers. After all the original code is Java and it should be primarily treated as such. A JDWP debugger makes much more sense to me.
Having worked with GWT since it birth, I am strongly advising towards this direction.
Also, I consider IDE based debugging much more preferable compared to Browser debugging.

**Comment by tbroyer** [comment] 2020-06-16 15:01
That ship has sailed years ago, I think everyone liked DevMode despite its flaws, but it's no longer possible to make it work. There were discussions at the time on possible alternatives, including some prototypes (incl. [one based on synchronous XHR](https://github.com/Legioth/devmodejs), which are also gone from browsers), but only Google had the resources to actually build something, and it was SDM.
If you have ideas for an alternative **and** the resources to build it, please open a discussion in gwt-contrib (I, for one, still believe it should be possible with remote debugging protocols; see https://code.google.com/archive/p/gwt-in-the-air/wikis/DesignOOPHM.wiki but it's more than 10 years old; the XHR-based prototype would tend to prove it).
In the mean time, this issue is not the place for such discussions.

**Comment by eliasbalasis** [comment] 2021-01-16 15:52
I believe I have found a permanent solution to the runtime Jetty classpath issues under Eclipse and "Google Plugin for Eclipse".

It all boils down to the nature of classpath resolution under "Google Plugin for Eclipse".

In short:

"Google Plugin for Eclipse" does not respect Maven class-path exclusions, decorations or the "test" scope.

This leads to incompatible class-path generation and as a consequence can produce unexpected runtime failures during run/debug of GWT applications within Eclipse.

"test" scope dependencies are always included in the final class-path
while
excluded dependencies (using <optional>) are still propagated to "Google Plugin for Eclipse".

To effectively battle such problems, without sacrificing the "Google Plugin for Eclipse" advantage, the most suitable solution is considered the use of a single dependency chain stream, dependency version overriding and exclusion of incompatible dependencies.

With "Eclipse IDE" being an integral part of the development approach, this is a necessary evil.

In more detail:

"Google Plugin for Eclipse" when running "DevMode" starts a "Jetty" container with normal JavaSE classloading priority.

> gives priority to the parent/system classloader. This avoids the issues of multiple versions of a class within a webapp, but the version the parent/system loader provides must be the right version for all webapps you configure in this way

This implies that webapp classloader (WEB-INF/lib) is always searched first before the parent/system classloader.

In othe words, inherit all of your applications dependencies through a single one on which you can structure the parent classpath.

Finally, exclude from your GWT Eclipse project any dependencies that Jetty fails to check at runtime.
This will exclude the JARs from being copied into the Jetty WEB-INF/lib folder but they will still be available from the parent classpath at runtime.

Of course you have to force your project to run with the Jetty dependencies your version of GWT was built with, using Maven techniques.

This recipe has perfectly worked for my projects and regardles of GWT/Jetty version used.

I will soon publish a Github project for this so that we can all share thoughts.

**Comment by eliasbalasis** [comment] 2021-04-18 16:14
A workaround has been found.

(see #9720)

>study https://github.com/eliasbalasis/eclipse-gwt-recipe
>
>Import this Maven project into Eclipse
>and
>use "GWT Eclipse Plugin" with "Super Development Mode" or any other combination.
>
>This will reproduce the problem.
>
>Enable exclusions section around `<artifactId>jetty-annotations</artifactId>` at `modules\gwt-web-eclipse\pom.xml` to fix the >problem (read explanation in comments section).
>
>I still strongly believe that the GWT classpath must be aligned with that of the associated Jetty though

**Comment by diskostu** [comment] 2021-07-13 09:04
Still no news on this? Support for Jetty 9.2.x ended in 2018 (!).

**Comment by niloc132** [comment] 2021-09-16 21:28
Also commented in https://github.com/gwtproject/gwt/issues/9720, but placing a note here - I just pushed a build to https://repo.vertispan.com/gwt-snapshot/ and to my gwt fork with an upgrade to the latest jetty and htmlunit release. It is passing tests in gwt itself, and also some simple app testing that I've done made, but more rigorous tests would be good to make sure no surprises pop up. 

https://repo.vertispan.com/gwt-snapshot/com/google/gwt/gwt-dev/2.10.0-htmlunit-upgrade-SNAPSHOT/ etc to get the artifacts from maven
https://github.com/niloc132/gwt/tree/htmlunit-upgrade to get the source changes to upstream HEAD.

Please note that I made the jetty upgrade to ensure that latest htmlunit is behaving well, and not as a tacit acceptance of running jetty from inside gwt - this is still not a good idea. That said, if there are fixes we can make to smooth this upgrade path, I'm not opposed to considering them.

**Comment by shrhoads** [comment] 2022-01-02 16:20
https://www.icoa.com/gwt-with-jetty-9-4/ has a build with jetty 9.4 and support for https code server.

**Comment by niloc132** [comment] 2022-06-09 15:19
GWT 2.10 will be released in the next few days, marking this as closed.

**Closed by niloc132** 2022-06-09 15:19 UTC
