### ISSUE TITLE
move GwtQuery code to gwt-site project

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#8144] opened 2015-06-10 19:16 UTC
Originally reported on Google Code with ID 8149

```
Currently the GwtQuery code is located in the app engine project, but it should be located
in the gwt-site project, so that it can be tested an developed locally as well.
```

Reported by `dankurka@google.com` on 2013-05-18 02:37:50

**Comment by tbroyer** [comment] 2017-03-05 20:49
Dupe of #8274

**Closed by tbroyer** 2017-03-05 20:49 UTC
Labels: Category-Website
