### ISSUE TITLE
Type of parameter Number is not usable by but exposed to JavaScript. [unusable-by-js]

### ISSUE THREAD

**Issue by slavap** [gwtproject/gwt#9586] opened 2018-01-05 07:09 UTC
Is it possible to eliminate this warning for Number parameters? I cannot use Double, because of compatibility reasons, I'm trying to emulate some java.time classes based on js-joda javascript library, and there are many java methods with Long parameters, which cannot be passed to js via jsinterop. So declaring them as Number works quite good, except a lot of these unusable-by-js warnings.

**Comment by niloc132** [comment] 2018-01-05 14:54
`com.google.gwt.dev.jjs.impl.JsInteropRestrictionChecker` says you can add `@SuppressWarnings("unusable-by-js")`. It also seems to report at the end of the output the message

> Suppress "[unusable-by-js]" warnings by adding a `@SuppressWarnings(\"unusable-by-js\")` annotation to the corresponding member.

if any such warning was emitted, or at least it should (see `checkProgram`).

**Comment by slavap** [comment] 2018-01-05 17:11
@niloc132 I know about annotation. The question is why this warning is shown for Number? Seems working fine and passing down to js code without any problem. And what is the best way to emulate some API with Long (in super folder) by jsinterop? I.e. I have working js code with numbers, and want to pass java Long there as actual doubles?

**Comment by niloc132** [comment] 2018-01-05 18:01
Hmm - through that logic, it would seem like you could permit CharSequence, Comparable, Serializable, or even Object as legal parameters without emitting that warning. These could not work as return types or a field or `@JsProperty` though.

Marking it as reopened until someone who knows that area better can evaluate, sorry for my having misunderstood the nature of your request.

**Comment by slavap** [comment] 2018-01-05 19:06
@niloc132 According to https://gwt-review.googlesource.com/c/gwt/+/13472/3//COMMIT_MSG
> The new implementation is also JsInterop friendly as small
numbers are real non-opaque numbers usable in javascript side
without any conversion. For example, even though time is
represented by long in java and double in javascript, both
uses less than 45 bits hence now interoperable.

"short" Long should work just fine in jsinterop (and that why my code is working), so unusable-by-js warning is really useless and confusing for both Number and Long.

**Comment by niloc132** [comment] 2018-01-05 19:25
Well, `long` may work, but as a declared parameter, `Long` will not - GWT will "box" that to be something like `{ "value_1" : 123.4 }`, plus of course the type details (to support `foo instanceof Long`) and instance methods (`foo.intValue()`). Unless your JS is passing around opaque `Long` values, in which case the unusable-by-js warning is "correct" again.

If you mean that you can pass a larger-than-int value from JS to Java where it accepts a Number, yes, but it will actually treat it as a java `double`. Remember that in JS, all numbers are effectively Java doubles (64 bit floating point numbers), even the ints, but the browser internals may actually represent them as some other type instead. Even a "short long" though will be a double, which you can see by trying to add one to a "medium" or "large" long, eventually you will start to lose precision in JS.

This is why GWT treats js numbers as Doubles, and lets Double be used to describe any js numeric value. Anything else is unsafe - and if you pass in any non-null js number (including "short longs", or ordinary ints) into a Java method that expects `java.lang.Number`, it will be an instance of Double, no matter what you started with in JS.

**Comment by slavap** [comment] 2018-01-05 20:17
@niloc132 Thanks, got it, so warning for Long is correct.
In my code I use java Number everywhere, and as I see it works fine both ways, "java to js" and "js to java". According to your explanation "under the hood" it's passed as double, which is ok. So the only "wrong" case is explicitly passing Long to Number param (and warning is correct in that case), right?
```java
public LocalDateTime plusDays(long days); // JDK original signature
public native LocalDateTime plusDays(@DoNotAutobox Number days); // my declaration in super
// I cannot declare param as long, because of "[ERROR] Parameter 'days': type 'long' is not safe to access in JSNI code

public native LocalDateTime plusMonths(@DoNotAutobox Long months); // is quite bad, because of [ERROR] The method plusMonths(Long) in the type LocalDateTime is not applicable for the arguments (int)

ld.plusDays(2); // this will pass 2 to js as double, right?
ld.plusDays(new Long(2)); // this will "fail" and pass Object to js, right?
```
So sounds like java Number is the best choice in my case. And I have to manually supress unusable-by-js on every method with Number (there are many, and annotation is not supported on class level :-( )

**Comment by niloc132** [comment] 2018-01-05 20:36
Do not expect `Number` to work correctly in cases of "java to js" - if you return `Number` from Java, this permits you to return `java.lang.Integer` or `java.lang.Long` or even `java.lang.BigDecimal`, none of which will work "correctly" when they get to JS. If you define a `native` method with Number parameters, unexpected things may happen and break as well - I had understood you to be saying that you were defining Java code, and calling from JS, not defining `native` code and calling it from Java.

>        ld.plusDays(2); // this will pass 2 to js as double, right?
>        ld.plusDays(new Long(2)); // this will "fail" and pass Object to js, right?

The first will work, but only because of `@DoNotAutobox`, but that is an internal annotation, and no guarantees are made about it continuing to work in the same way in future releases. As far as JS goes, for `native` method parameters, you only have a few safe param types: any primitive except `long`, `JsNumber`, or `Double`. As a _parameter to a native method_, the `Number` type isn't safe, since someone could pass in a large long, a `BigDecimal`, or some non-Double type (though as said, your annotation is solving that for the moment). The second might work, since 2 is a small enough long, and you have the annotation to unbox, but I make no promises.

The `js-joda` which you are wrapping in jsinterop _expects_ java double/Double values, and it will not be able to handle other numbers. I'm sure it is internally expecting to only handle integers, but JS as a language doesn't have support (yet?) for non-int number types. You can prove this to yourself easily, try to handle a huge number like `11111111111111111` in JS - it will show up as `11111111111111112`, since it is using more than 53 bits of precision. Under 53 bits and you _can accurately represent integer values in a Java Double_, and it sounds like that fits your use case.

Since you are providing wrapping around the JS impl anyway, I would do the conversions from long to Double at that point anyway. If you let users pass in any `Number`, you might get surprises at runtime.

**Comment by slavap** [comment] 2018-01-05 20:55
@niloc132 In case of "normal" wrapping of js-joda I would use Double of course. But in my case I'm trying to provide super emulation for some java.time classes, so I'm stuck between JDK method signatures and jsinterop restrictions :-( I understand java Number is "wrong" choice, but it's flexible enough for both Java and jsinterop. Or may be should follow JDK signatures exactly (with long), and implement translation layer, which is just passing these long to native methods as double. Sounds like a lot of boring manual job, but it's "safe". Currently I've got most of the code by just converting typescript definition to java with https://github.com/ltearno/typescript2java

**Comment by niloc132** [comment] 2018-01-05 21:14
I would encourage that, yes - it will be safer than risking arbitrary Number types causing confusing runtime errors. `@DoNotAutoBox` is the only way that `Number` will consistently work, and even then you risk issues with unexpected number types. Explicitly handling longs and translating them to doubles lets you decide if you either lose precision, or warn to the user that something bad has happened. 

These bugs end up being very sneaky if you aren't careful - I'm dealing with another one right now where JS internally is tracking a java `int`, but let it get larger than java's Integer.MAX_VALUE, which then causes errors when it gets to the server...

**Comment by slavap** [comment] 2018-01-05 21:18
@niloc132 Perhaps solution in my case could be ability to tell compiler somehow that long is ok to use in @JsType(isNative=true) class:
[ERROR] Parameter 'days': type 'long' is not safe to access in JSNI code
prevents me from declaring: public native LocalDateTime plusDays(long days);
And long will work up to 45 bits without any problem as "native" js double, which is enough in the most cases. And no manual translation layer is needed then.

**Comment by jnehlmeier** [comment] 2018-01-06 15:46
IMHO any Java API that takes long/Long, but passes that long/Long to some external JS should do a range check to avoid unexpected behavior. GWT itself fails on it as well in case of the Date class for example (see: https://github.com/gwtproject/gwt/issues/4857) which can lead to weird behavior in your code. 

Using long/Long without any range check, only makes sense if you stay within GWT code, because then the GWT compiler will take care of the long/Long via [LongLib](https://github.com/gwtproject/gwt/blob/master/dev/core/super/com/google/gwt/lang/LongLib.java)).

So what you have is:
```
Java: Long.MAX_VALUE          = 9223372036854775807 = 2^63 - 1
JS:   Number.MAX_SAFE_INTEGER = 9007199254740991    = 2^53 (IEEE 754 mantissa)
GWT:  MAX SmallLong           = 17592186044415      = 2^44 - 1
```
Your super-source now has two choices:
1. Only allow GWT SmallLongs and convert them to double
2. Also allow GWT BigLongs but before converting to double, also check that the BigLong is a JS safe integer (Number.isSafeInteger()).

If you allow longs larger than Number.MAX_SAFE_INTEGER you get rounding errors when such a long will be represented as a double in JS and thus date algorithms in an app may behave wrong/unexpected. So yes, your super-source code will either become pretty annoying to write, or you must clearly document that users of your library should never ever use such a long and live with the compile warnings.

**Comment by slavap** [comment] 2018-01-06 19:42
@jnehlmeier I really would prefer to have an ability to tell compiler it’s ok to use long in jsinterop code. Of course there are limitations, but “short” long is already native js compatible. So “Parameter 'days': type 'long' is not safe to access in JSNI code” must be warning, not error, or even better controllable by annotation.

**Comment by jnehlmeier** [comment] 2018-01-06 19:50
https://github.com/gwtproject/gwt/blob/master/dev/core/super/com/google/gwt/core/client/UnsafeNativeLong.java

But it doesn't buy you anything, because your code must work if someone calls
```java
localDateTime.plusDays(Long.MAX_VALUE);
```

**Comment by slavap** [comment] 2018-01-06 23:47
@jnehlmeier Thanks, looks exactly as what I need, will check it later tonight. From Java point of view you are absolutely right, but don’t forget in my case I’m just wrapping js library, and under the hood it’s all doubles anyway.

**Comment by tbroyer** [comment] 2018-01-07 16:37
> don’t forget in my case I’m just wrapping js library, and under the hood it’s all doubles anyway

Exactly, and that's why you don't want to let anything else through: no "big longs", no `java.lang.Integer` or similar wrapper types, no `BigInteger` or `BigDecimal` or other `Number` subclass; only `double` or `java.lang.Double` as they're interchangeable.

So you should use something like:
```java
private native LocalDateTime plusDays(double days);

@JsOverlay public LocalDateTime plusDays(long days) {
  // XXX: maybe add range checks here
  return plusDays((double) days);
}
```

and let the compiler do its optimization work (if all your longs are "small longs", I'd expect the cast to double to be a no-op)

**Comment by slavap** [comment] 2018-01-08 03:19
@tbroyer Yep, cast to double will be no-op, but number of jsoverlay methods will be huge, and they are not "free", i.e. size and performance will be affected, and a lot of manual code (or changes to typescript2java translator) as well.

**Comment by slavap** [comment] 2018-01-08 04:04
@jnehlmeier Thanks again, @UnsafeNativeLong works fine!

@niloc132 @tbroyer But now I've got another weird problem. For some reason the name of LocalDateTime getClass().getName() is com.google.gwt.core.client.JavaScriptObject$, though I have disableClassMetadata=false in my pom.xml
So is it super-source problem or something else? Or it's intended for @JsType(isNative=true) cases?

**Comment by rluble** [comment] 2018-01-08 16:55
Classes that are not Java classes do not have any useful class metadata. That includes JSOs and JsType(isNative=true).  The Java abstractions over these classes are very thin.

**Closed by rluble** 2018-01-08 16:55 UTC

**Comment by slavap** [comment] 2018-01-08 22:19
@rluble Nice :-( So there is no any way to make getName() working for these classes?

**Comment by slavap** [comment] 2018-01-09 03:30
@rluble It was hard, but I've found the way to make JSO/JsType(isNative=true) to be more Java friendly, so now LocalDateTime.class and d.getClass().getName() are both working, though I have to manually "register" all needed classes:
```java
    /** Sets the proper class name for JsType/JSO class. */
    static native void setupJsType(Class<?> clazz, String packageName, String compoundName) /*-{
      clazz.@Class::packageName = packageName;
      clazz.@Class::compoundName = compoundName;
      clazz.@Class::simpleName = compoundName;
    }-*/;

// then on very early app init stage:
setupJsType(LocalDateTime.class, "java.time", "LocalDateTime");
...
```
Everything is slightly "hackish", but I'm able to use java.time classes on both server and client sides, and able to pass them through Errai marshalling, so my initial goal is kind of achieved.

@niloc132 @jnehlmeier @tbroyer May be there is a better way?

**Comment by jnehlmeier** [comment] 2018-01-09 09:03
@slavap sure, make your super-source a normal java class and delegate to an internal `@JsType(native = true)` class. That's how GWT itself does it in its emulation code. See [Date](https://github.com/gwtproject/gwt/blob/master/user/super/com/google/gwt/emul/java/util/Date.java) emulation for example.

**Comment by slavap** [comment] 2018-01-09 09:26
@jnehlmeier OMG :-) Now I know why my resulting GWT js code is huge :-)
