### ISSUE TITLE
A call to Window.alert() or Window.confirm() will cause the client side to hang in Firefox but not in Chrome or IE.

### ISSUE THREAD

**Issue by geoffritchey** [gwtproject/gwt#9152] opened 2015-07-02 13:31 UTC
A call to Window.alert() or Window.confirm() in gwt 2.7.0 will cause the client side to hang in Firefox 38.0.5 but not in Chrome or IE.  The alert box and message appear.  You can click the acknowledge button and the box will disappear but no other form controls are usable after that, as if you remain in MODAL-DIALOG mode.

**Comment by jnehlmeier** [comment] 2015-07-02 16:07
Can't confirm that with our apps and FF 38.0.5 (however we use some GWT 2.8 snapshot).

But given that GWT directly calls the JavaScript window.alert() / confirm() functions through JSNI without any additional magic, it is likely to be an issue in your own app code. Also IE 11 uses the same GWT permutation as Firefox so if it works in IE 11 but not in FF 38 then it sounds more like a FF bug (maybe triggered through your own app code).

**Comment by geoffritchey** [comment] 2015-07-02 20:12
Worked in 2.5.1.  Upgraded libraries and Firefox; then crash.  The debugger shows it is throwing a makeAssertionError with the message "Negative entryDepth value at entry " + entryDepth.  If it's just my code I think it would be odd that it should work in Chrome and IE.  The exception point is not part of my code and the call is of course an extremely simple one liner ---  Window.assert("message");.  I don't have a makeAssertionError exception as part of my code.

**Comment by geoffritchey** [comment] 2015-07-02 20:24
Maybe related to this:  https://code.google.com/p/google-web-toolkit/issues/detail?id=7926

**Comment by tbroyer** [comment] 2015-07-02 21:28
It indeed looks like a regression in Firefox, reintroducing the bug from version 18 where code can actually be executed concurrently. Playing a bit with the jsfiddle linked from #7923, I can reproduce it. Adding a call to `console.trace()` in `enter()` I can clearly see that `checkHistoryCycle()` is called "from within" (or more likely concurrently to) `onClick()` (it's then displayed as `onClick</` in the call stack). This is clearly a violation of JS and/or HTML5.

The one big difference from the jsfiddle in GWT 2.7 though, is that History no longer uses a timer, so there probably is another timer somewhere in your code that triggers the bug in Firefox.

But it is undoubtedly a bug in Firefox IMO.

Cc @gkdn @dankurka

**Comment by tbroyer** [comment] 2015-07-02 21:35
See https://jsfiddle.net/49b5gf8j/1/embedded/result/

At some point, you'll see in the dev console:

```
"enter: entryDepth=1"
console.trace():
  enter()
  entry0()
  checkHistoryCycle()
  doClick/<()
  entry0()
  doClick()

"exit: entryDepth=1"
console.trace():
  exit()
  entry0()
  checkHistoryCycle()
  doClick/<()
  entry0()
  doClick()
```

Feel free to use that jsfiddle as a repro case if you want to file a bug on https://bugzilla.mozilla.org/

**Comment by geoffritchey** [comment] 2015-07-02 22:30
https://bugzilla.mozilla.org/show_bug.cgi?id=1180005

**Comment by jnehlmeier** [comment] 2015-07-03 08:24
Yeah I have also seen the message "Negative entryDepth value at entry X" in SDM in FireFox from time to time. I didn't really bother because it was super rare with our app and assumed it was a FireFox issue as the GWT code was fine.

**Comment by tbroyer** [comment] 2015-07-03 09:01
@geoffritchey You're not going to have your bug reports prioritized (and fixed) if you don't give all the information you have. I updated the Bugzilla report with the information I put above; but I also noted that you only put the `makeAssertionError` bit (which was quite important; I think the `entry0` and assertion helped you find that older issue with Firefox 18) on the old issue tracker (and in the Bugzilla report, but they don't know GWT and shouldn't have to).

Note: I don't close the issue now as we have some work to do on the issue tracker wrt labels et al. But consider this issue closed as a "known browser quirk".

**Comment by geoffritchey** [comment] 2015-07-23 18:43
In desperation I downloaded the FF beta, which is at 40.0, and a very quick overview seems to indicate everything is working fine in that version.

**Comment by nitinsbuzz** [comment] 2016-09-01 09:04
Similar issue. Only on mobile devices. Specifically safari. Running more tests. Did an online check on js lint but no errors. Really weird.

**Comment by tbroyer** [comment] 2016-09-01 09:28
Closing as per my earlier comment last year.

@nitinsbuzz If you can reproduce the bug using the JSFiddle, then it's not a GWT bug. If you can't but still have a bug with your GWT code, then it's likely a different issue.

**Closed by tbroyer** 2016-09-01 09:28 UTC
Labels: Browser-Quirk
