### ISSUE TITLE
GWT RequestFactory/Editor Framework null values don't reach server

### ISSUE THREAD

**Issue by dfht** [gwtproject/gwt#9275] opened 2016-02-02 13:37 UTC
I have many editor widgets that work well until I null out the values in them.
When I do so, the null doesn't ever seem to get propagated to the server.

I have my own service layer decorator that overrides the setProperty method, and for null values it never seems to arrive at the method.

Is this a known issue or is there something I'm not doing?
I use request factory in tandem with the editor framework, and always call flush on the screen prior to firing the request (and as I say it all works fine for everything except nulling out a value - a perfectly reasonable thing to want to do I think :)).

**Comment by dfht** [comment] 2016-02-02 13:56
More important information:
I override the 'validate' method in my ServiceLayerDecorator, and I only get this behaviour with nulls after the object has failed validation (i.e. some ConstraintViolations are returned from the validate method) and I fix the violations then re-fire the request. What is the point of the validate returning me back if I can't just fix the errors flush, and then re-fire the initial request? Also, what is special about the treatment of null here? It seems fine until the validation fails....? The validation is a check that at least one from a list of fields is null. When I re-fire the request after null-ing one out it still has the last (non-null) value in the entity (and doesn't go near the setProperty method fro the nulled out values).

**Comment by dfht** [comment] 2016-02-02 14:14
Simple use case:
In your own custom service layer decorator, just override the validate method to return a constraint violation if a particular field is null. Then enter a non null value and save the item. Then the validation will fail and return you to the screen. Next, null out the field and re-fire the initial request. It should still raise the validation error as the null value doesn't seem to get propagated to the server . You can verify this by overriding the setProperty on your SLD and debugging or logging. You can also verify in the same way that non-null values do propagate.

**Comment by tbroyer** [comment] 2016-02-02 14:19
Could you setup a repro case? (e.g. a small repo on GitHub)

**Comment by dfht** [comment] 2016-02-02 14:31
Hi Thomas,
 I can work around this issue by rebuilding the request each time (currently I cache it and re-fire it after fixing validation errors). However, this seems inefficient. Is this actually what I should be doing, or is the re-firing of a request after fixing validation errors something that should be supported?
If I do just re-build the request, do these old requests hand around (e.g. cached by the context) in any way and is there any way they can accidentally get re-fired anyway (I seem to recall these kind of problems in the past, which I think is why I started caching the requests in the first place).

Yes  I can probably make a simple sample to illustrate the bug. It's tricky, as I work on a huge model based application platform, so of course I cannot give you my example directly. However I guess a very simple first principles case can probably be knocked up in an hour or so.

Any more thoughts on this and what I should be doing are welcome.....

**Comment by dfht** [comment] 2016-02-02 15:06
I guess the fact that rebuilding the request works fine does at least rule out the editor framework (I'd pretty much ruled that out anyway as debugging in Chrome showed that the flush did gather the nulls from the editor widgets)

**Comment by tbroyer** [comment] 2016-02-02 15:08
> is the re-firing of a request after fixing validation errors something that should be supported?

It should work yes (and is how you're supposed to handle validation errors)

**Comment by dfht** [comment] 2016-02-02 15:12
That's what I thought... I guess I need to make a basic example so that you can reproduce it and to rule out anything odd that I might be doing. I'll let you know when I have something,
cheers

**Comment by dfht** [comment] 2016-02-03 11:02
Thomas,

I've created an example project now and shared it on GitHub.
The repository is 
[https://github.com/dfht/RFNullAfterViolationBugReport].

It's a very simple and self-contained Eclipse Google Web Application project that (assuming you have Eclipse with the Google plug-ins) can just be run with the embedded Jetty server via 
'Run As/Web Application (GWT Super Dev Mode)'. It's about as simple as I could make it whilst still bringing in Request Factory and Editor Framework, and does seem to be showing the behaviour I described.

Simply enter into the 'GWT User' text field and press send. The User will will be validated on the server by checking that the name is null. If not it will fail validation (so only null gets accepted). First, enter a non-null value to see it fail validation. Then empty out the field and press send again and you should see that the null value never makes it to the server, and the validation fails again with the old value.
Putting breakpoints in the setProperty and validate methods on MySLD should show the fact that it goes to the server with the old stale value after the field is blanked out (not to setProperty but to only validate in this case - as though the null hasn't been recognised as a change and sent over in the proxy/auto bean by RF). 

By the way, all this is with GWT 2.7.0 and jdk1.8.0_31, and I am using Chrome '48.0.2564.97 m' (which has given me at least two other headaches regarding removal of SVG 1.1 code and flex-box tinkering, but that is another story as they say :)). 

cheers,

Darren

**Comment by dfht** [comment] 2016-02-03 11:10
In fact it just never seems to send anything across when the field is empty at all, regardless of prior validation failure! It's like it regards nulls as the field is unchanged even if there was a non-null value in it before. By the way, in my application I have observed this with a number of other custom editors of mine that are nothing to do with text fields, so I don't think the editor being a text field is anything to do with this problem.

**Comment by dfht** [comment] 2016-02-03 11:16
Oh, and if you do find out what the problem is, then please let me know if there are any workarounds I could do whilst I wait for a fix (other than rebuilding the request each time instead of caching it - which definitely works but seems wrong).....
cheers,
Darren

**Comment by tbroyer** [comment] 2016-02-03 11:41
I understand this is a contrived example but the issue might be similar in your project: TL;DR you're misusing entities and locators. You're using a singleton `User` instance, so when the server receives data, it asks the locator for the user instance for the corresponding ID (which returns the singleton instance), then applies changes to it (from the received request) and then validates the object. When validation fails, your server object has been modified and is invalid: this is bad™ (I'm not even talking about concurrent accesses to the object). When you set the property back to null on the client, the next request won't include any change for the property (it was null when the object was initially retrieved and `edit()`ed, and is still null at the time `fire()` is called), so on the server side, the locator will return the singleton `User` instance (which has been made invalid by the previous request) and doesn't do any change before validating it (so validation fails again).
If your `UserLocator` cloned the `User` on `load` and _merged_ it back into the singleton on `save`, I'd bet it'd solve your problem (I unfortunately don't have time right now to test it myself, I only quickly looked at the code on GitHub)

**Comment by tbroyer** [comment] 2016-02-03 11:44
> If your `UserLocator` cloned the `User` on `load` and merged it back into the singleton on `save`, I'd bet it'd solve your problem (I unfortunately don't have time right now to test it myself, I only quickly looked at the code on GitHub)

Sorry, `save` is obviously in your `DomainService`, not in `UserLocator`.

**Comment by dfht** [comment] 2016-02-03 12:19
No, the singleton is just for convenience so I don't have to bring databases into it etc.
It has nothing to do with the way it works in my project.

**Comment by dfht** [comment] 2016-02-03 12:22
In my project the user is always gotten fresh from a database and populated (it's all hibernate finds from my real locators etc.) so please rule that out as a reason. As I say, the singleton is just to make the example minimal and self-contained. The issue isn't anything to do with this.

**Comment by dfht** [comment] 2016-02-03 12:28
Don't know why you're going on about concurrency in a clearly contrived  example designed to illustrate a single bug and just run by one person at a time. You are trying to infer far too much about the true nature of my overall application. The whole point of the simple example was to shield out all that noise and concentrate on the simple fact that the null doesn't make it over to the server on the setProperty.

**Comment by dfht** [comment] 2016-02-03 12:29
It takes just a few minutes to test btw. I went to the trouble of making it simple and easy so that it was nice and quick for you.

**Comment by dfht** [comment] 2016-02-03 13:14
In actual fact, in my real example  I want to actually persist the errors (believe it or not), as they are being made on a 'change request' object. We have the concept of an object to make changes on such that we can come back to it later and fix errors before (eventually) submitting it as the final version (when it becomes an actual new 'entity' version). I changed my example to clone and apply instead of edit the original object, and it seems you were right. The example now works as it should. However, as I say, for me I actually want to persist the error, so my example was unwittingly similar to the reality. 

For me, my problem I think is that I do the entire RF request in a transaction, so everything gets persisted (even errors). Although this is what I want in this case, it's not what RF expects and so causes weird behaviour like this.

I need to 
1. Not do the whole request within a transaction - only the actual save etc.
2. Not use RF validate to validate my application in this way (as I -unusually I know- want to persist errors!).
3. Do the validate on the fetch of the changes object instead and return it as part of what is returned to a user. This is perhaps more sensible anyway, as users can see the problems after getting a 'changes in progress' object rather than waiting until submission. 

So I think I will make my fetches return objects that wrap the entity (changes object) and validation constraints (after doing a validate whilst fetching) and set them on population into the screen. I think my validation is definitely different to the usual notion of validation that was designed into RF, and I had somewhat shoe-horned it in.

Thanks for pointing me in the right direction and making me think about it from a different angle (albeit somewhat coincidentally unless you have psychic powers ;)).

Darren

**Comment by tbroyer** [comment] 2016-02-03 13:50
Don't get me wrong: all I was saying is that the singleton in the example **is** a problem that would in itself explain the behavior; and that if you `edit()` an entity with a null property and that property is still `null` when you `fire()`, it's **expected** that "the null value doesn't reach the server", and that holds true even when reusing the context after a constraint violation.
The node about concurrency accesses is because it would unfortunately not surprise me to find such code in the wild, so better note it "just in case" than silence it.

I just found some time to test your sample project and, as I predicted, with your latest change that clones/merges to the singleton, I don't reproduce the issue.

FWIW, I ran the project with `mvn package` followed by `mvn gwt:run` using the following Maven POM:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project
  xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <groupId>test</groupId>
  <artifactId>test</artifactId>
  <packaging>war</packaging>
  <version>1.0-SNAPSHOT</version>
  <name>GWT Maven Archetype</name>

  <properties>
    <!-- Convenience property to set the GWT version -->
    <gwtVersion>2.7.0</gwtVersion>

    <!-- GWT needs at least java 1.6 -->
    <maven.compiler.source>1.7</maven.compiler.source>
    <maven.compiler.target>1.7</maven.compiler.target>

    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.google.gwt</groupId>
        <artifactId>gwt</artifactId>
        <version>${gwtVersion}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>com.google.gwt</groupId>
      <artifactId>gwt-servlet</artifactId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.google.gwt</groupId>
      <artifactId>gwt-user</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.google.gwt</groupId>
      <artifactId>gwt-dev</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.11</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
<sourceDirectory>${project.basedir}/src</sourceDirectory>
<testSourceDirectory>${project.basedir}/test</testSourceDirectory>
<resources>
  <resource>
    <directory>${project.basedir}/src</directory>
  </resource>
</resources>
<testResources>
  <testResource>
    <directory>${project.basedir}/test</directory>
  </testResource>
</testResources>

    <!-- Output classes directly into the webapp, so that IDEs and "mvn process-classes" update them in DevMode -->
    <outputDirectory>${project.build.directory}/${project.build.finalName}/WEB-INF/classes</outputDirectory>

    <plugins>

      <!-- GWT Maven Plugin -->
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>gwt-maven-plugin</artifactId>
        <version>2.7.0</version>
        <executions>
          <execution>
            <goals>
              <goal>compile</goal>
              <goal>test</goal>
            </goals>
          </execution>
        </executions>
        <!-- Plugin configuration. There are many available options, see 
          gwt-maven-plugin documentation at codehaus.org -->
        <configuration>
          <runTarget>RFBugReport.html</runTarget>
          <modules>
            <module>com.mycompany.RFBugReport</module>
          </modules>
<warSourceDirectory>${project.basedir}/war</warSourceDirectory>
        </configuration>
      </plugin>
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-war-plugin</artifactId>
  <version>2.6</version>
  <configuration>
    <warSourceDirectory>${project.basedir}/war</warSourceDirectory>
  </configuration>
</plugin>
    </plugins>
  </build>
</project>
```

**Comment by tbroyer** [comment] 2016-02-03 13:53
Ha, just saw your last comment, so closing.

And yes, in a project where we wanted to persist invalid objects, we also persisted constraint violations (validation was asynchronous) and retrieved them from the server whenever we needed them (and transforming them to `ConstraintViolation` objects on the client-side so we could pass them to the editor driver for display), so your reasoning is correct.

**Closed by tbroyer** 2016-02-03 13:53 UTC
Labels: Category-RequestFactory

**Comment by dfht** [comment] 2016-02-03 13:55
I'm digressing now, and this issue should perhaps be closed. Out of interest, if I don't do the entire request in a transaction, then I'm left with the problem of fields on my entity that may be lazily populated (hibernate/JPA annotations etc.) which when accessed outside of a transaction for the first time will simply not be able to return it's values (detached object etc.). That's why I wrapped everything in a transaction in the first place I recall. Do you know how people usually deal with this? Cloning the object and later applying changes from a clone somehow seems to take away the value that RF brings as in this case I might as well write my own transport layer that records what has changed (I've done that before in a previous job and was very much hoping to avoid it lol). I guess what I want in particular is to wrap (in a transaction) not just the fetch of the locator etc. but also the code whereby the objects values are read from the entity and set into the 'proxy' (auto bean or whatever). Is there a way of doing that (considering that a lot of the RF Servlet code is closed off private methods etc.)?

**Comment by dfht** [comment] 2016-02-03 14:03
And of course I want the bit where it sets stuff from the proxies back into the entity prior to validation to not be in a transaction. So I guess fine control of transactionality within the RF Servlet without cloning and owning the class is what I'm wondering is possible or not....

**Comment by dfht** [comment] 2016-02-03 14:21
I guess if I'm keeping all changes then it doesn't matter actually :). Thanks again

**Comment by tbroyer** [comment] 2016-02-03 14:42
> Out of interest, if I don't do the entire request in a transaction, then I'm left with the problem of fields on my entity that may be lazily populated (hibernate/JPA annotations etc.) which when accessed outside of a transaction for the first time will simply not be able to return it's values (detached object etc.). That's why I wrapped everything in a transaction in the first place I recall. Do you know how people usually deal with this?

I'm a bit "allergic" to JPA, and even more to lazy loading, so I very well might be wrong, but wouldn't it work if you use the "open session in view" (aka session-per-request) pattern? (while keeping transactions scoped to your service methods only). This, at least, is how you're "supposed" to use RequestFactory with JPA; so if that's not what you're doing, maybe give it a try.

**Comment by dfht** [comment] 2016-02-03 16:11
Final question for today (I promise :)). Do you know if there's a short-cut or easy way to pass ConstraintViolations across from a DomainService on the server such that they get converted to the correct client side objects? I see they aren't 'transportable' in the defined sense for RF.
There must be some way, as the server side violations found by the SLD are obviously propagated back and converted. I want to return a set of them from the server via a domain service method.  Sometimes it would be nice if all serialize-able classes without a declared interface with  'ProxyFor'  could just be assumed 'transportable', 'GWT serialized' and sent down the wire like what happens for RPC calls. In other words, all serialize-able classes then become transportable in the request factory sense. Otherwise I guess I make my own ConstraintViolationValueProxy and convert it to a 'real' one on the client. It's all just so I can make errors for specific attributes show alongside fields when I do the 'validation on fetch'  (like they do when using the SLD based validation mechanism).
I could use RPC, but then that's a separate call to the server and I want to return the EntityProxy object and its constraint violations back together from a DomainService method in one go.....
No worries if not - I'll just make my own ConstraintViolationProxy and work it out from there.....
Cheers,
    Darren

**Comment by tbroyer** [comment] 2016-02-03 17:21
Actually, RF uses a `ViolationMessage` AutoBean on the wire, and wraps it into a `MyConstraintViolation` on the client side to adapt it to the `ConstraintViolation` API.
You can see how `ConstraintViolation`s are transformed into `ViolationMessage`s at https://github.com/gwtproject/gwt/blob/c9c32256f6ffb8ca69f50693a06b91bc25331fef/user/src/com/google/web/bindery/requestfactory/server/SimpleRequestProcessor.java#L586-L620, and the client-side adapter is at https://github.com/gwtproject/gwt/blob/c9c32256f6ffb8ca69f50693a06b91bc25331fef/user/src/com/google/web/bindery/requestfactory/shared/impl/AbstractRequestContext.java#L418-L489
This is not usable directly from your code, but at least you can mimick it with your own `ConstraintViolationValueProxy`.

**Comment by dfht** [comment] 2016-02-03 17:37
Thanks again Thomas

**Comment by dfht** [comment] 2016-02-04 13:41
I should probably post this elsewhere, but anyway....
I'm trying the approach we discussed of passing the validation failures across within a (value) proxy.
I use a 'ValueProxied' class V1 for this that wraps an entity bean E1. There's an outer 'ValueProxied' class V0 that in turn wraps V1, as well as wrapping another entity proxy E0 that contains (in it's object graph) a reference to the same entity bean E1. Somehow, when it all gets back to the client, the proxy representative of an E1 instance (x say) within the entity E0 is not the same as the one directly within V1 (so two different proxy representatives of the same entity in a single object graph).
On the server side the instances of E1 are the exact same object, but the client side proxies are different.
This seems wrong.... Would you expect this behaviour?

V0(VP)
|           \
V1(VP)     E0(EP)
|                       |
E1(EP)           E1(EP)

**Comment by dfht** [comment] 2016-02-04 13:42
Apologies for my mangled 'diagram' :) - It looked better before I posted it

**Comment by dfht** [comment] 2016-02-04 13:53
Actually, forget that. I see once again it is an error in our code. They actually aren't the same object. just that some fool has duplicated a variable in the same hierarchy so what seemed like something set into the same variable actually isn't. Grrrrrrrrrrrr

**Comment by dfht** [comment] 2016-02-04 14:46
Assuming multiple reps of the same object are acceptable, then is there any client side utility method to verify that two objects do come from the same source object on the server? I can do it using my own id's but it seems like I shouldn't have to if you know what I mean........ What happens with the ViolationMessage etc. seems to invoke a lot of internal code and I don't really see how I can follow that approach, so I'm just wrapping up the beans  in the constraints directly so I can access the proxies on the client. The problem comes when reconciling which object an error came from on the client (due to the multiple representation issue I seem to be seeing). I was hoping for a simple equality check to just work...
