### ISSUE TITLE
Performance regression in long emulation in 2.8.0 RC2

### ISSUE THREAD

**Issue by ainsley** [gwtproject/gwt#9398] opened 2016-08-12 19:30 UTC
Long-bitwise-and emulation seems to have become approx 70%-80% slower between 2.7.0 and 2.8.0 RC2. I have not tested for the 2.8.0 RC1 to 2.8.0 RC2 delta.

This seems to affect IE, Edge, Chrome, and Firefox.

The following application was built to test the bitwise and regression, I link to 2.7.0 and 2.8.0 RC2 compiled versions of the exact same app. Source code is included on the main page. I can create a github project with the source too if required.

**2.7.0 test**

http://iro-iro.xyz/gwt9398/issue9398_270/

**2.8.0 RC2**

http://iro-iro.xyz/gwt9398/issue9398_280rc2/

**Comment by jnehlmeier** [comment] 2016-08-12 22:31
Only used the `performTest` method and removed most of the UI stuff. Then compiled it using `-strict -optimize 9 -style PRETTY`

**GWT 2.7:**

```
515ms (iterations/ms: 1941.7475728155339)
434ms (iterations/ms: 2304.147465437788)
408ms (iterations/ms: 2450.9803921568628)
409ms (iterations/ms: 2444.987775061125)
397ms (iterations/ms: 2518.891687657431)
397ms (iterations/ms: 2518.891687657431)
409ms (iterations/ms: 2444.987775061125)
404ms (iterations/ms: 2475.2475247524753)
```

![2 7](https://cloud.githubusercontent.com/assets/1703797/17638537/e8ce0af6-60ea-11e6-87bc-019db5697ae5.png)

```
function and(a, b){
  return {l:a.l & b.l, m:a.m & b.m, h:a.h & b.h};
}
```

**GWT 2.8:**

```
588ms (iterations/ms: 1700.6802721088436)
569ms (iterations/ms: 1757.469244288225)
581ms (iterations/ms: 1721.170395869191)
558ms (iterations/ms: 1792.1146953405018)
570ms (iterations/ms: 1754.3859649122808)
608ms (iterations/ms: 1644.7368421052631)
571ms (iterations/ms: 1751.3134851138354)
551ms (iterations/ms: 1814.8820326678765)
```

![2 8](https://cloud.githubusercontent.com/assets/1703797/17638540/ec039678-60ea-11e6-8bca-e7f6bc588a1d.png)

```
function and_0(a, b){
  return createLongEmul(and(isSmallLong0(a)?toBigLong(a):a, isSmallLong0(b)?toBigLong(b):b));
}
```

So for this concrete case the new `and(a,b)` implementation is significantly slower. I guess the implementation would probably be faster if GWT would check that `a` and `b` are the same type of longs and in case of small longs use normal bitwise `&` and in case of big longs use the implementation of GWT 2.7. Conversion to big long must only occur if `a` and `b` are different types of long.

**Comment by ainsley** [comment] 2016-08-12 22:48
Maybe it's worth testing if the bitwise or suffers regressions in the same way too.

**Comment by jnehlmeier** [comment] 2016-08-12 23:00
I used Chrome for profiling (Dev Tools -> Profiles -> JavaScript CPU profile)

Looking at GWT code I would say its possible to write test code that will be slower in GWT 2.8 for nearly all bit operations as they all convert small longs unconditionally to big longs and I assume thats what makes things slower. 

```java
  public static LongEmul not(LongEmul a) {
    return createLongEmul(BigLongLib.not(toBigLong(a)));
  }

  public static LongEmul and(LongEmul a, LongEmul b) {
    return createLongEmul(BigLongLib.and(toBigLong(a), toBigLong(b)));
  }

  public static LongEmul or(LongEmul a, LongEmul b) {
    return createLongEmul(BigLongLib.or(toBigLong(a), toBigLong(b)));
  }

  public static LongEmul xor(LongEmul a, LongEmul b) {
    return createLongEmul(BigLongLib.xor(toBigLong(a), toBigLong(b)));
  }

  public static LongEmul shl(LongEmul a, int n) {
    return createLongEmul(BigLongLib.shl(toBigLong(a), n));
  }

  public static LongEmul shr(LongEmul a, int n) {
    return createLongEmul(BigLongLib.shr(toBigLong(a), n));
  }

  public static LongEmul shru(LongEmul a, int n) {
    return createLongEmul(BigLongLib.shru(toBigLong(a), n));
  }
```
In your test code only the first AND uses a big long (0x3ff000000000000L), all other ANDs use small longs, so conversion to big long happens a lot.

**Comment by gkdn** [comment] 2016-08-12 23:01
We already did a detailed perf comparison (we have plenty of long benchmarks - see the related repo) and we are aware of some performance degradation on bit operations. However overall gains are way more significant especially on more common operations, we decided to proceed with the change. 
See the perf comparison details here:
https://gwt-review.googlesource.com/#/c/13472/3//COMMIT_MSG

As Jens pointed out, we don't have a fast path for bitwise operations but I'm not sure about the effectiveness of that if there was one; given that we need to handle the signs as well. Feel free send a patch with results from our existing benchmarks.

**Comment by ainsley** [comment] 2016-08-12 23:27
This is quite tough, I understand it's impossible to optimize for everything but this really impacts the bottom line performance of my application, and any other GWT application that involves JavaCC generated compilers significantly.

I worked on the JavaCC 6.1 release (java compiler compiler) _specifically_ to be able to generate parsers that are GWT compatible. I blogged about it here : 

http://consoliii.blogspot.com/2014/04/creating-gwt-compatible-parser-using.html

I have been working on an (as yet unreleased) parser-centric GWT project for 4 years full-time solo. I *really* need every ounce of performance I can get in order to be able to scale to very large document sizes. 

Lexing and parsing involves a lot of state handling logic and lots of string operations. JavaCC creates a "ParserTokenManager.java" class (which is a standard asset generated from a JavaCC language definition file) is littered with bitwise and operations on long typed primitives. In fact, there can be millions of calls to these and-operations per compile, and this has reduced the overall responsiveness of the application by 30-50%. Incremental can reduce the overhead but occasionally a full compile is needed and slowing down by 50% is quite noticeable.

I don't want GWT 2.8.0 to slow itself down in general in order to speed up this one use-case. Might an option be to be able to use a compiler flag to speed up the and operations specifically for this use case? Or is the solution as you see it to accept the regression, for the sake of the greater good?

**Comment by gkdn** [comment] 2016-08-13 01:41
We actually already accepted the regression for the sake of greater good.
I think at this point it is little bit late and also plenty of extra complexity to add a flag for this. Could you somehow use 32 bit int for this?

**Comment by ainsley** [comment] 2016-08-13 13:41
Agreed, avoiding longs seems to be the way forward here.

**Comment by jnehlmeier** [comment] 2016-08-13 13:47
Hmm or use longs that are larger than 44 bits so that GWT uses big longs for your bit operations. Then the performance difference shouldn't be that large as GWT 2.8 would then nearly act as GWT 2.7.

**Comment by gkdn** [comment] 2016-09-02 03:04
Closing the bug since we are not planing to take any action here.

**Closed by gkdn** 2016-09-02 03:04 UTC
Labels: Category-JRE
