### ISSUE TITLE
JsInterop produces an messy namespace structure

### ISSUE THREAD

**Issue by manolo** [gwtproject/gwt#9201] opened 2015-10-08 07:20 UTC
When exporting a class with nested namespace: 

        @JsNamespace("foo.bar") @JsExport
        public class Hello {...}

if we inspect  the dom we should see something like:

        window.foo -> Object{bar: Object}
        window.foo.bar -> Object{Hello: function ....}

but instead it is assigning the Hello constructor to all the nodes:

       window.foo -> Object{bar: Object,  Hello: function ....}
       window.foo.bar -> Object{Hello: function ....}

so as we can use the constructor with any name which is incorrect.

      new window.foo.bar.Hello();
      new window.foo.Hello();

I have not tested what happens if we have the same class in different namespaces, but we could expect unexpected results depending on the order how class are exported.

For existing nodes it does not assign the constructor though.

**Comment by gkdn** [comment] 2015-10-08 22:16
I am having trouble reproducing this. Perhaps  you are using a very old version? Can you add a test JsTypeTest that reproduces the problem?

**Comment by gkdn** [comment] 2015-10-08 22:42
Oh I saw your patch and the problem. I think I couldn't reproduce the problem because probably the namespace was already defined elsewhere hence wasn't assigned to the constructor.

**Comment by manolo** [comment] 2015-10-09 05:56
Yes, the problem is when there are nodes in the namespace which do not work. We at vaadin always use the SNAPSHOT for web components, so as we realise very soon changes in API.

**Closed** 2015-11-05 22:14 UTC
