### ISSUE TITLE
Page scrolls up when clicking on tree items in a screen not shown on displayed page part	

### ISSUE THREAD

**Issue by annalabrador** [gwtproject/gwt#9496] opened 2017-03-09 10:05 UTC
**GWT version: 2.8
**Browser (with version):** UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
**Operating System:**  any

---

##### Description

Steps to reproduce the problem:
In order to show you the issue, I created a small demonstrator here : https://www.apartment-baden.com/test/

1. If one clicks on tree items being visible on load of page, the click action works - a popup shows up "Test on click outer child item"
2. Now, if you scroll down some items to a non visible tree item on page load, e.g. to item 40 and click on it, the page scrolls up instead of showing the popup.

What is the expected behavior?
Action linked to the tree item is shown

What went wrong?
instead, page scrolls up

Did this work before? yes, up to Chrome 54
Same issues in Microsoft Edge 

##### Steps to reproduce

See description

##### Known workarounds

no - or use Firefox

##### Links to further discussions
We asked Chrome support already, but they do not seem to find a solution

https://bugs.chromium.org/p/chromium/issues/detail?id=681382

**Comment by jnehlmeier** [comment] 2017-03-09 10:28
Closing because it is a duplicate of https://github.com/gwtproject/gwt/issues/9475 (which also provides a CSS workaround)

The root cause is that Chrome does not return correct layout values of the clicked tree item and thus the focusable div element is updated with wrong position values.

**Closed by jnehlmeier** 2017-03-09 10:28 UTC
